/* ------------------------------------------------------------------ *
 *  The full audit log.
 *
 *  68 findings from one read-through of every product surface, captured
 *  2026-07-25. Severity is the auditor's.
 *
 *  REWRITTEN 2026-08-04 to docs/spec/lab-voice.md. The original wording ran to
 *  a 133-character average title and an 858-character average `why`, in long
 *  clause-stacked sentences the owner could not act on ("I can't even address
 *  them because most of the time I have no idea what it's talking about").
 *  Titles and prose are now roughly 79 and 390. Nothing was dropped except the
 *  eight Groups findings, which described a surface that no longer exists.
 *
 *  `evidence` is deliberately UNTOUCHED: it is the receipts, it sits behind a
 *  toggle, and file paths and quoted code are supposed to be exact.
 *
 *  `verified` means the claim was independently re-checked against the source
 *  or recomputed, not just reported. Everything in the chrome group was
 *  verified by hand. The rest is marked honestly.
 * ------------------------------------------------------------------ */

export type Severity = "looks-broken" | "looks-fine-but-thoughtless" | "genuinely-good";

export type Finding = {
  id: string;
  surface: string;
  title: string;
  evidence: string;
  why: string;
  idea: string;
  severity: Severity;
  verified: boolean;
};

export const SURFACES: { key: string; label: string; best: string }[] = [
  { key: "browse", label: "Collection + Directory", best: "The shared facet pills. Every filter speaks one language: plain when idle, canopy with an x when set. The pill prints its own label rather than echoing the select, so it can never leak a raw option id, and the pill IS the active-filter chip, which removes a whole redundant row. Best of all is the rule that sort stays neutral even though it always carries a value, because canopy means \"this is narrowing your results\" and sorting never narrows. Someone wrote that rule down and then obeyed it." },
  { key: "letters", label: "Letters", best: "The letter title's entrance. The heading rises 6px while a cinnamon rule draws itself underneath, left to right, fading out at the end so it tapers like an inked stroke instead of stopping dead. Transform and opacity only, the accent used as an accent, and it is the one gesture here that reads as editorial rather than generic. Runner-up: the nudge that suggests turning a long post into a Letter. No cap, no red counter, no blocking, and the best copy in the feature." },
  { key: "settings", label: "Settings + pickers", best: "The house run. Committing a house closes the panel and opens the next year that still needs one, skipping years already filled and stopping rather than wrapping, so a four-year career is six clicks with nothing to dismiss in between. Every one of those choices is argued for in the comments. Whatever the picker becomes, keep that behaviour." },
  { key: "support", label: "Support, About, first run", best: "The Houses step in onboarding. The year rows are pre-filled from dates you already gave, so nobody types a year. The open picker hands itself to the next unfilled year, so a whole school career is one click each with no re-aiming. And the answer draws back as a live chain that collapses runs of the same house into tinted spans. The empty and one-row cases are genuinely handled. Runner-up: the QR crossfade, which deliberately exits without a spring, because a QR code should never wobble." },
  { key: "messages", label: "Messages + notifications", best: "The search pill. It animates real width and padding rather than using Motion's layout trick, because scaling and counter-scaling an eightfold change reads as stretching. Two springs, one per direction, the closing one damped so it cannot overshoot. The icon is deliberately not a motion element, so it can never be skewed. Every number in that file has its reason written beside it, including a recorded finding that Motion will not animate gap." },
  { key: "feed", label: "Feed, post card, comments", best: "The comments accordion's single clock. One observer on the measured content is the only source of truth, so the first open, the comments arriving over the network, and a reply you just posted all grow the panel on the same spring, instead of a second jumpy re-open. The close was deliberately slowed after the open read as a snap. The meta row above it is the same quality: its gap is documented as three rejected attempts, measured with a pixel probe." },
  { key: "chrome", label: "Global chrome + tokens", best: "The Button's automatic icon centring. It works out whether a button leads or trails with an icon, correctly either way, whether the icon arrives as a live component or as an already-rendered svg. It refuses to shift an icon-only button, and shaves a 4px optical step off whichever side holds the glyph. The comment explains exactly why the obvious CSS cannot do it. Every icon-and-label pill in the app is balanced with no per-call tuning. Runner-up: the global rule that animates background and border but never colour, so the heart hits red on the first frame instead of fading through a dark middle." },
  { key: "catchups", label: "Catch-ups", best: "The published Round's table of contents. One scroll-spy hook rendered two ways, a sticky rail on desktop and a chip row on mobile, with a tiebreak so the highlighted item is what you are reading rather than merely what is on screen. The marker moves on a measured offset using the sidebar's own spring instead of Framer's layout prop. Three real decisions in forty lines." },
];

export const FINDINGS: Finding[] = [
  {
    id: "browse-1",
    surface: "browse",
    title: "On a phone, 71% of the map card is empty beige",
    evidence: "`style={{ height: \"min(72vh, 640px)\" }}`, src/components/directory/alumni-map.tsx:532, against `const W = 900; const H = 460;`, alumni-map.tsx:50-51",
    why: "The map keeps its own 2:1 shape inside a box with a fixed height, so it can only ever fill part of it. At 390px wide the map draws 350x179 inside a 607px box. That is 429px of nothing, more than a whole phone screen. The \"not yet on the map\" pill ends up 400px below the map it is talking about.",
    idea: "Drop the fixed height and let the card take the map's own aspect ratio. Better on a phone: refit the projection to a taller frame and crop to where people actually are, instead of spending half the screen on the Pacific.",
    severity: "looks-broken",
    verified: false,
  },
  {
    id: "browse-2",
    surface: "browse",
    title: "Every filter throws you out of the Map, including the map's own city chips",
    evidence: "`setBrowseView(hasFilter ? \"people\" : \"map\");` inside a `useEffect` keyed on `[users, nextCursor, hasFilter]`, src/components/directory/directory-client.tsx:122-126; the chips at `onClick={() => updateFilters(\"city\", c.city)}`, directory-client.tsx:578",
    why: "Click \"Bangalore 84\" on the map and it does narrow the pins, then instantly swaps you to a card grid so you never see it happen. The data side already supports filtering in place; the client throws that away on every filter change. The view control also gains a segment and slides sideways under your cursor as you click it.",
    idea: "Stop resetting the view when a filter lands. Choose a starting view on first load only. If People has to appear, add it at the end so Map and Batches never move.",
    severity: "looks-broken",
    verified: false,
  },
  {
    id: "browse-3",
    surface: "browse",
    title: "A page for finding people centres the names, so no two share a left edge",
    evidence: "`className=\"card-elevated flex h-full flex-col items-center rounded-[var(--radius)] border border-border bg-card p-5 text-center transition-colors duration-200 group-hover:border-canopy/40\"`, src/components/directory/profile-card.tsx:27, in `grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3`, directory-client.tsx:522",
    why: "Names sit centred in tall 182px cards, so your eye has to re-find each one. Sixty people is about 3,950px of scrolling. The same person renders as a tidy 56px left-aligned row in the map's side panel, so the better version already exists in this file. Cards also stretch to match their tallest neighbour, and a blank profile shouts \"MEMBER\" in the loudest small type on the page.",
    idea: "Use the map panel's row: 40px bird, name on a shared left edge, batch and city as one dim line. Sixty people then cost about 1,300px. When there is no batch year, print nothing rather than \"Member\".",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "browse-4",
    surface: "browse",
    title: "Both pages count the results per filter option, then hide the count",
    evidence: "`cities: cityGroups.map((c) => c.city)`, src/app/(main)/directory/page.tsx:274 (the groupBy above it at :244-249 selects `_count: { city: true }` and sorts `[{ _count: { city: \"desc\" } }, { city: \"asc\" }]`); identically `areaOptions={areaGroups.map((g) => g.area!).filter(Boolean)}`, src/app/(main)/collection/page.tsx:42",
    why: "The dropdown is ordered by how many people match, but the numbers are not shown, so a ranked list looks shuffled. Picking \"Ooty\" and getting one, or \"Bangalore\" and getting 84, feels identical until you click. Two other controls on the same page do show their counts.",
    idea: "Pass the count through beside the label and set it right-aligned and dim. No new queries. It also lets you dim the options that would return nothing.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "browse-5",
    surface: "browse",
    title: "A photo archive that dates every photograph by when it was uploaded",
    evidence: "`className=\"pointer-events-none absolute inset-0 flex items-end bg-gradient-to-t from-black/65 via-black/0 to-black/0 opacity-0 transition-opacity group-hover:opacity-100\"`, src/components/collection/collection-client.tsx:46; and `meta={new Date(photo.createdAt).toLocaleDateString(\"en-GB\", {...})}`, src/app/(main)/collection/[id]/page.tsx:141-145",
    why: "The contribute form asks what year and month the photo was taken. Nothing ever reads them back. A photo from March 1994 shows a \"1990s\" chip above the line \"14 Jul 2026\", so the upload date is the more precise of the two. In the grid, the caption and the credit only appear on hover, which never happens on a phone: the Collection there is a wall of unlabelled squares.",
    idea: "Show the real date, phrased to match how sure the contributor was: \"March 1994\", \"1994\", \"1990s\", \"date unknown\". Demote the upload line to \"added by Ravi, Jul 2026\". Put the caption under each tile at rest, the way a contact sheet does.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "browse-6",
    surface: "browse",
    title: "The Collection's sort is unreadable, and Load more moves what you already saw",
    evidence: "`className=\"[column-gap:0.75rem] columns-2 sm:columns-3 lg:columns-4\"`, src/components/collection/collection-client.tsx:367, paired with `setPhotos((prev) => [...prev, ...data.photos]);`, collection-client.tsx:137",
    why: "CSS columns fill downward, so with four columns the second-newest photo is under the newest and photo 7 is back at the top. \"Oldest first\" reads as four separate timelines. Load more re-balances all four columns, so the photo you were reaching for jumps somewhere else. The skeleton promises a neat square grid and then resolves into a ragged one.",
    idea: "Pick one story. Either a real masonry that keeps reading order and appends without reflowing what is above, or a plain contact sheet of squares with the caption and year underneath, which sorts legibly and matches the skeleton already written.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "browse-7",
    surface: "browse",
    title: "The Batches view is a shape you cannot see: forty identical boxes",
    evidence: "`className=\"grid grid-cols-3 gap-3 sm:grid-cols-4 md:grid-cols-5 lg:grid-cols-6\"`, src/components/directory/directory-client.tsx:591, with the Faculty tile appended after the loop at :606-618 using the identical `card-elevated group flex flex-col items-center rounded-[var(--radius)] ... p-4 pt-3.5`",
    why: "Forty years become forty identical boxes. How many people are in each is the interesting part, and it is set in the smallest type on the page while the year is bold. Rows wrap at three to six columns depending on width, so decades never line up and you cannot see \"the 2010s\" as one thing. Faculty is not a year at all and sits last, after the 1970s.",
    idea: "Let the count be the thing you see: a bar, or a tint that deepens with the size of the batch. Group rows by decade with a small label, ten to a row so they align. Lift Faculty out to its own row on top.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "browse-8",
    surface: "browse",
    title: "The map's pin sizing, clustering and tooltip guard are properly worked out",
    evidence: "`return 9 + Math.sqrt(count / Math.max(1, max)) * 22;` with the comment \"Area proportional to count, so a 200-count city is not 200x the diameter\", src/components/directory/alumni-map.tsx:112-115",
    why: "This is the one place on either page where someone worked out the encoding instead of defaulting to something. Pin area scales by square root, which is the right answer and rarely the first one anybody reaches for. The tooltip is derived rather than stored, so a stale one is impossible rather than merely unlikely. Touch gets a 44px target while mouse hit areas stay exactly as they were.",
    idea: "Worth adding: one line of total, \"1,204 people across 137 cities\". Right now the only number the map states outright is how many people it could not place, and nothing tells you that leaf pins are single cities and sky pins are merged ones.",
    severity: "genuinely-good",
    verified: false,
  },
  {
    id: "letters-1",
    surface: "letters",
    title: "Forty letters render as forty identical slabs",
    evidence: "`_count: { select: { comments: { where: { isHidden: false } }, likes: true } },`, src/app/(main)/letters/page.tsx:53, and `l._count` appears nowhere in the JSX (lines 81-129)",
    why: "The page fetches the like and comment counts and then shows neither, so a short note from this morning with 40 comments looks exactly like a 25-minute essay from March with none. Each one costs about 240px of scroll to convey its title and nothing else. The spec asked for the counts on the card.",
    idea: "Tier it. The newest letter leads at full width with its dek and its live comment count; everything after drops to a 64px row with the date on a left rail. Group the rows by month. Five letters in 500px instead of 1,280.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "letters-2",
    surface: "letters",
    title: "The feed shows a letter better than the Letters page does",
    evidence: "Feed: `<h3 className=\"mt-2 font-heading text-xl ...\">` under the post header, then `<span className=\"mt-3 inline-flex items-center gap-1 text-sm font-semibold text-leaf\">Read this letter`, src/components/posts/post-card.tsx:241-252. Index: byline last, `<div className=\"mt-4 flex items-center gap-2.5 border-t border-border pt-3.5\">` and `<span className=\"ml-auto inline-flex items-center gap-1 text-sm font-semibold text-leaf opacity-0 transition-opacity group-hover:opacity-100\">Read`, src/app/(main)/letters/page.tsx:104, 123",
    why: "In the feed the byline sits above the title, which is the order you actually decide by, and \"Read this letter\" is always visible. On the Letters page both are inverted: the byline is pushed under a 31px rule, and the read link is hidden until hover, so on a phone it never appears at all while still holding its space. Two people built these two cards and neither looked at the other.",
    idea: "Use the feed's order here: byline above the title, which also removes the separator band. Replace the hover-only link with the read time and the comment count, both always visible.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "letters-3",
    surface: "letters",
    title: "The one word that is identical on every card is the most legible thing on it",
    evidence: "`<div className=\"flex items-center gap-1.5 text-[10.5px] font-bold uppercase tracking-[0.13em] text-cinnamon\">` … `<span className=\"text-muted-foreground/70\">· {readTime(l.content)} min read</span>`, src/app/(main)/letters/page.tsx:87-90; dek at `text-[14.5px] leading-relaxed text-muted-foreground` line 101",
    why: "The cinnamon word \"Letter\" prints forty times down a page called Letters, next to forty feathers, at 3.69:1. The read time, the only thing that changes from row to row, sits at 2.60:1. The dek, which is the pitch for a twenty-minute read, is 4.40:1 at 14.5px, under AA.",
    idea: "Delete the word. Give the read time full muted ink and put the date or the comment count beside it. Lift the dek to a darker soft ink so it reads like a dek and not a caption.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "letters-4",
    surface: "letters",
    title: "The one long-form reading surface has no paper under it and no measure",
    evidence: "`<article className=\"mx-auto max-w-[680px]\">`, src/app/(main)/letters/[id]/page.tsx:84 (no bg-card, no radius, no shadow), body at `className=\"mt-7 whitespace-pre-wrap font-heading text-[17px] leading-[1.8] text-foreground ...\"` line 129. Compare `className=\"max-w-[64ch] whitespace-pre-wrap font-heading text-[16.5px] leading-[1.78] text-foreground\"`, src/components/profile/about-prose.tsx:20",
    why: "A letter floats on the recessed page colour while every other piece of content in the app sits on a cream card. The feature is called a Letter and there is nothing under it. Lines run 72 to 77 characters where the spec asked for 66, and a three-sentence profile bio got a proper measure while the 4,000-word essay got a round pixel number. There are no paragraph elements at all, so the rhythm is stuck at exactly one blank line.",
    idea: "Put it on paper: a cream sheet at 16px radius, in the same 768px column as the index so clicking in does not shift the page sideways. Split the body into real paragraphs at 66 characters, and let the first one open the way an editorial page does.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "letters-5",
    surface: "letters",
    title: "[Fixed 2026-07-30] Every letter's byline began with a stray middot",
    evidence: "`{formatBatch(l.author.batchType, l.author.batchYear)} ·{\" \"}`, src/app/(main)/letters/page.tsx:113 and the same at src/app/(main)/letters/[id]/page.tsx:117; `if (batchYear == null) return \"\"`, src/lib/utils.ts:60",
    why: "The account that owns every letter on the site has no batch year, so the batch string came back empty and the separator printed anyway: \". 18 July 2026\". That was 100% of letters, in both the index and the reading view. The fix already existed elsewhere in the codebase and the feed rail was quietly using it.",
    idea: "Done. metaLine() owns the separator rule now, and a dot only appears between two things that both exist. The Anonymous account's byline is simply the date.",
    severity: "looks-broken",
    verified: false,
  },
  {
    id: "letters-6",
    surface: "letters",
    title: "Letter 41 disappears, and a finished letter has no way onward",
    evidence: "`take: 40,`, src/app/(main)/letters/page.tsx:56 (no skip, no cursor, no count query, no load-more anywhere in the file). At the end of a letter: `<LetterEngagement ... />`, src/app/(main)/letters/[id]/page.tsx:148, which terminates in `<CommentsSection ... alwaysOpen />` and nothing else.",
    why: "The index has no paging, no total and no search, so the 41st letter ever written is unreachable and nothing on the page admits it exists. And after twenty minutes of reading, the page ends at a comment box: no next letter, no more from this author, no link back except scrolling all the way to the top.",
    idea: "Give the index a spine: month headers with a count each, and an \"Earlier letters\" pill. At the foot of a letter, before the comments, put the previous and next letters as two compact rows, plus more from the same author.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "letters-7",
    surface: "letters",
    title: "The page explains what a Letter is three times in 250 pixels",
    evidence: "`subtitle=\"Longer pieces from the valley. Essays, tributes, travelogues, reflections.\"`, src/app/(main)/letters/page.tsx:63; `A longer piece, taken slowly. A tribute, a reflection, a letter home.`, src/components/letters/letter-composer.tsx:27; `A letter is for the things too long for the feed.`, src/app/(main)/letters/page.tsx:76; plus `letter: \"Write your letter to the valley. Take your time.\"`, src/components/posts/create-post-form.tsx:122",
    why: "On an empty Letters page you get three definitions stacked inside about 250px, two of them almost word for word, and a fourth in the editor placeholder the moment you click. The empty state is also a second cream card identical to the composer above it, so first run reads as two boxes both saying \"write a letter\".",
    idea: "Keep the composer's line. It is the best of the four and it sits where the action is. Make the header subtitle a plain count instead. Delete the empty-state card and let the composer fill the space.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "letters-8",
    surface: "letters",
    title: "The skeleton is the wrong size, so the list jumps 138px when it loads",
    evidence: "`<div className=\"rounded-[var(--radius)] border border-border bg-card p-6\"><div className=\"skeleton-warm h-20 w-full rounded-md\" /></div>`, src/app/(main)/letters/loading.tsx:10-12, and `<div className=\"skeleton-warm h-8 w-8 rounded-full\" />` line 22",
    why: "Every piece is off: the composer block is 128px against a real 68px, the avatar 32px against 40, each card 195px against 221. The content jumps up about 138px the instant data lands, on a page whose whole mood is unhurried.",
    idea: "Match the real numbers. Better, have the skeleton and the real card render one shared shell, so the two can never drift apart again.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "settings-1",
    surface: "settings",
    title: "The house picker asks the same question nine times, with no \"same as last year\"",
    evidence: "`<div className=\"grid grid-cols-2 gap-1.5\" role=\"group\" aria-label=\"Pick one or more houses\">` src/components/common/house-picker.tsx:142, pills at :151-156 `\"flex min-h-10 items-center justify-center rounded-full border px-2.5 py-2 ... selected ? \\\"border-canopy bg-canopy text-white\\\" : \\\"border-border bg-mist/50 text-foreground\\\"\"`",
    why: "Twenty-two houses render as twenty-two identical pale pills in no obvious order, so every pick is a scan of a 500px grid, repeated four to nine times. Six of them are literally named after a colour, and the app already has a per-house colour map one file away that this picker does not use. Most people were in one or two houses for a whole career, and there is no way to say so.",
    idea: "Make the editor the trail. Years as a ribbon, the houses below it as coloured swatches grouped into their real families: colours, trees, mountains and rivers. Pick one and drag along the years to paint a run, so \"Neem 2014-18, Palm 2018-19\" is two gestures instead of five identical menu trips. Keep the pills for keyboard use.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "settings-2",
    surface: "settings",
    title: "Onboarding pays you back for entering houses; settings does the same work and shows nothing",
    evidence: "onboarding: `{journey.length > 0 && ( <div ref={chainRef} className=\"flex flex-wrap items-center justify-center gap-x-1.5 gap-y-2 rounded-2xl border border-border bg-mist/60 p-[var(--space-m)]\">` src/components/onboarding/steps/houses-step.tsx:194-197. Settings' Houses card has no equivalent: src/components/settings/settings-form.tsx:617-680 jumps straight from the copy line to `{houseRows.map((row) => (`.",
    why: "Both screens mount the same picker over the same data. Onboarding draws a live tinted chain as you pick, so the chore visibly makes something. Settings, which is where corrections actually happen, gives back a row of flat text chips. That leaves three different house colour languages in one product: onboarding's tints, the profile's three-colour cycle, and settings' none.",
    idea: "Hoist one houses chain with one tint source and put it at the top of the settings Houses card, animating as picks land. Use the same component on the profile, so the thing you build in settings is the thing that ships.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "settings-3",
    surface: "settings",
    title: "Uploading a photo silently throws away every other unsaved edit on the page",
    evidence: "`<SettingsForm key={user.updatedAt.toISOString()} user={user} />` src/app/(main)/settings/page.tsx:53, against `setPhotoUrl(result.photoUrl ?? null); toast.success(\"Photo updated\"); router.refresh();` src/components/settings/settings-form.tsx:217-219 (and the identical pattern at :228-229, :243-245, :253-255).",
    why: "The photo box saves the moment you choose a file; the field two rows below it waits for Save. Nothing on screen says so, and Discard cannot undo the photo it claims to be reverting. The remount that causes this was added for a real reason and never reconciled with the four actions that save without going through the save bar.",
    idea: "Either stage the photo and upload it on Save with everything else, or stop remounting on every change: key on a save counter the form itself controls, and mark the live-saving boxes \"saved just now\" so the mixed model is at least visible.",
    severity: "looks-broken",
    verified: false,
  },
  {
    id: "settings-4",
    surface: "settings",
    title: "The Houses card ignores the years you typed two cards above it",
    evidence: "`const missingHouseYears = missingYears(houseRows, user.yearJoined, user.yearLeft);` src/components/settings/settings-form.tsx:146 and `const houseAnchorYear = user.yearJoined ?? user.yearLeft ?? currentYear - 1;` :183, while the live values sit in state at :130-131 `const [yearJoined, setYearJoined] = useState(...)`.",
    why: "Two cards describe the same fact, when you were at school, and they do not talk to each other. For someone filling this in for the first time the years are still blank, so the picker starts at last year: reaching 1994 means clicking \"Earlier year\" 31 times and then deleting 27 rows you did not want.",
    idea: "Read the live years out of the form rather than the saved user, and re-seed the rows when they change, keeping any picks already made. Then let the Houses section state its range in words, editable inline, so the two cards read as one fact.",
    severity: "looks-broken",
    verified: false,
  },
  {
    id: "settings-5",
    surface: "settings",
    title: "The header-picture preview shows neither the right image nor the right treatment",
    evidence: "`style={{ backgroundImage: `url(${coverPhoto || \"/images/collection/v1.webp\"})` }}` src/components/settings/settings-form.tsx:394, with `<div className=\"absolute inset-0 bg-gradient-to-b from-black/10 to-black/30\" />` at :396.",
    why: "A preview has one job, to answer \"what will this look like\", and this one answers it wrong twice. It also spends 112px of the card on a picture that says nothing about your own header, and because the path is hardcoded the two will drift apart the next time the photo pool changes.",
    idea: "Ask for the same image the profile asks for, and lift the profile band's filter and fade into one component both use. If they have to differ, say so plainly: \"we pick a valley photo for you\", and show which one.",
    severity: "looks-broken",
    verified: false,
  },
  {
    id: "settings-6",
    surface: "settings",
    title: "The boxes inside a card are exactly the card's colour, and one is rounder than the box holding it",
    evidence: "`<div className=\"flex items-center gap-4 rounded-[var(--radius)] border border-border bg-paper/50 p-4\">` src/components/settings/settings-form.tsx:350, and inside the header box at :393 `<div className=\"relative h-28 overflow-hidden rounded-xl border border-border bg-mist bg-cover bg-center\">` nested in :391 `<div className=\"space-y-3 rounded-[var(--radius)] border border-border bg-paper/50 p-4\">`.",
    why: "The recessed fill and the card fill are the same hex, so a nested box has no fill difference at all, only a hairline. That is the flat, weightless nesting you noticed. The cover preview then breaks the rule outright, putting a 20.8px corner inside a 16px one. The token that exists for this job, mist, is used correctly one card away.",
    idea: "Use mist for the recessed boxes and step the radius down: card, then sub-box, then preview. Then drop the sub-box border. With a real fill difference the stroke is redundant, and the card stops reading as three stacked frames.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "settings-7",
    surface: "settings",
    title: "Settings hand-rolls its title, so it is a different weight in the fifth different column",
    evidence: "`<h1 className=\"font-heading text-3xl font-bold text-foreground\">` src/app/(main)/settings/page.tsx:48, versus the shared `<h1 className=\"font-heading text-[30px] leading-none tracking-[-0.02em] text-foreground\">` src/components/layout/page-header.tsx:37.",
    why: "Every other page routes its title through PageHeader and gets 30px regular. Settings sets its own bold, with different tracking and a 6px taller block, and no subtitle where its siblings have one. Across the nav the title's left edge lands at five different positions, 220px apart end to end, so clicking through slides it sideways and changes its weight.",
    idea: "Use PageHeader here, so weight, tracking and leading are shared. Then pick two column widths, one for reading and one for browsing, and map every route onto them, so a page title has at most two possible positions.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "settings-8",
    surface: "settings",
    title: "Tapping a writing prompt pastes the question into your answer and leaves no cursor",
    evidence: "`onClick={() => { setAbout((a) => (a ? `${a}\\n\\n${p} ` : `${p} `)); markDirty(); }}` src/components/settings/settings-form.tsx:432-435, with `const ABOUT_PROMPTS = [\"What do you do now?\", \"A memory from the valley\", \"What brought you back?\"];` at :73.",
    why: "A prompt should unblock writing, not become part of it. The chips never dim once used and never go away, so a finished bio still carries three unanswered-looking questions above it. Nearby, a \"0 / 4000\" counter greets you on the first render, telling someone writing three warm sentences that they are at 0.05% of expected length, and the card called Houses opens with an Admission number field.",
    idea: "Have the chips insert nothing: focus the box and show the prompt as a rotating ghost placeholder, dimming that chip once there is an answer. Show the counter only near the limit. Move Admission number into the batch card and rename that card \"Your years at Rishi Valley\".",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "settings-9",
    surface: "settings",
    title: "The house run auto-advance is genuinely well designed and must survive any rethink",
    evidence: "`function advanceHouseYear(fromYear: number) { const next = [...houseRows].sort((a, b) => a.year - b.year).find((r) => r.year > fromYear && r.houses.length === 0); setOpenHouseYear(next ? next.year : null); }` src/components/settings/settings-form.tsx:171-176, with the in-panel year heading at src/components/common/house-picker.tsx:136-141 and `side={wide ? \"right\" : \"bottom\"}` at :134.",
    why: "This is the one part of the surface that was iterated rather than defaulted, and every decision is argued for in the code. Picking a house commits it and hands the panel to the next empty year, so a four-year career is six clicks with no dismissing in between. Years already filled are skipped, so one mid-career correction does not march you through the rest. It stops at the end rather than wrapping.",
    idea: "Keep the auto-advance, the year printed inside the panel, and the skip-filled-years rule if this ever becomes a trail. One real bug beside it: the popover has no maximum height, and the 22-pill grid is about 650px tall, which cannot fit under a trigger on a 390x844 phone.",
    severity: "genuinely-good",
    verified: false,
  },
  {
    id: "support-1",
    surface: "support",
    title: "The build-fund bar is invisible at zero, and its caption talks you out of giving",
    evidence: "`const BUILD_RECOVERED = 0;` (src/components/support/cost-bar.tsx:34); `const pct = Math.min(100, (BUILD_RECOVERED / BUILD_COST) * 100);` (:155); `className=\"mt-[var(--space-m)] h-5 w-full overflow-hidden rounded-full bg-mist p-1\"` (:176); `animate={shown ? { scaleX: pct / 100 } : { scaleX: 0 }}` (:186)",
    why: "The empty trough is 1.07:1 against its own card, so it reads as a faint dent rather than a bar waiting to fill. The count-up spends 950ms animating the character 0 over and over. And it is the last thing before the donate panel, ending on \"Nothing about the site changes if it never fills up.\" Nobody sat with this at zero; it was written for the day it is 40%.",
    idea: "Never draw a 0% bar. At zero, show a ladder of 80 ticks, one per five thousand rupees, so the first contribution visibly lights one. Better still, lead with the win: the monthly costs are already covered, so say that, and demote the build fund to one indented note with no bar at all.",
    severity: "looks-broken",
    verified: false,
  },
  {
    id: "support-2",
    surface: "support",
    title: "A funded fact and an unfunded one are drawn as identical twins, so the empty one reads as failure",
    evidence: "CostBar: `className=\"card-elevated mt-[var(--space-m)] rounded-[var(--radius-lg)] border border-border bg-card p-[var(--space-l)]\"` (src/components/support/cost-bar.tsx:105). BuildFundBar: the exact same string at :160, the same `flex flex-wrap items-baseline justify-between gap-x-[var(--space-m)]` title row (:107 / :162), and the same `h-5 w-full ... rounded-full bg-mist p-1` bar (:118 / :176).",
    why: "One card is a solved recurring cost at 100%, in all three brand colours. The other is an unfunded aspiration at zero. Same radius, same padding, same pill, stacked 16px apart. Identical form forces a comparison the content cannot survive: a full bar, then an empty one, on a page asking for money.",
    idea: "Give the one-off a different shape entirely. Either drop it out of card-space into a recessed note inside the monthly card, prose only, or change the metaphor: a pill for the recurring cost, a grid of 80 squares for the one-off. Two shapes, two meanings, no false comparison.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "support-3",
    surface: "support",
    title: "The only reward on the donation page cannot be delivered, and it links to a dev scratch page",
    evidence: "`Anyone who chips in gets to pick their own bird. Instead of the one you were given at random, choose any species from our` + `<Link href=\"/lab/birds-rv\" ...>collection</Link>` `of 50, to wear as your avatar across the site.` (src/app/(main)/support/page.tsx:91-99). And `// NOTE: \"/lab\" is temporary, design-direction mockups; remove before shipping.` (src/proxy.ts:53).",
    why: "Nothing anywhere writes the field that would give someone their chosen bird, so the perk cannot be handed over at all. The link goes to a 46-line mockup with no app chrome, no back link and no way to choose, on a route the code says to delete before shipping. And it sits below the ask as four lines of plain text, on a product whose signature is fifty hand-drawn birds.",
    idea: "Reorder to cost, then reward, then ask, and make the reward the picture: eight real bird glyphs at 56px above the QR panel, the last dimmed with \"+42 more\". Then either build the picker or change the copy to what is true today. A promise the product cannot keep is worse than no perk.",
    severity: "looks-broken",
    verified: false,
  },
  {
    id: "support-4",
    surface: "support",
    title: "Support and About skip PageHeader, so their titles are bolder and 172px further right",
    evidence: "PageHeader: `className=\"font-heading text-[30px] leading-none tracking-[-0.02em] text-foreground\"` inside `<header className=\"mb-6 ...\">` (src/components/layout/page-header.tsx:35-39). Support: `className=\"mt-[var(--space-m)] font-heading text-3xl font-bold tracking-[-0.02em] text-foreground\"` (src/app/(main)/support/page.tsx:39). About: the same `text-3xl font-bold` at src/app/(main)/about/page.tsx:14 inside `<div className=\"mb-10\">`.",
    why: "Six nav destinations render their title at 30px regular; Support, About, Settings and Admin render it bold with taller leading. The gap under the header is three different numbers. Horizontally the title jumps about 172px right the moment you click Support. Those two pages also lose the notification bell on desktop, because PageHeader is the only place it mounts.",
    idea: "Put both on PageHeader with the short nav-matching titles, and demote the current sentence-long h1 to a lead paragraph beneath it. That fixes the weight fork, the missing bell and the 172px jump in one move.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "support-5",
    surface: "support",
    title: "About explains a three-feature product that no longer exists, and contradicts the tour above it",
    evidence: "`<h3 className=\"font-semibold text-foreground\">Feed</h3>` / `Directory` / `Profile` - the entire \"How to use it\" list (src/app/(main)/about/page.tsx:47-70), directly beneath `<TakeTourAgainButton />` (:45). The tour's real stops are `route: \"/feed\"`, `\"/directory\"`, `\"/collection\"` (title `\"The Valley Collection\"`), `\"/catchups\"` (title `\"Catch-ups\"`), `\"/groups\"` (src/components/tour/tour-steps.ts:59-116). The sidebar ships eight destinations (src/components/layout/sidebar.tsx:57-68).",
    why: "Collection, Letters and Catch-ups appear nowhere on the one page whose job is explaining the site, so a newcomer meets a feather in the sidebar with no gloss anywhere. The button that starts the correct five-stop tour sits directly above the wrong three-item list, so the page disagrees with itself within 120px. Structurally it is one heading-and-paragraph pattern run eight times.",
    idea: "Make \"How to use it\" a real map: one row per surface with its actual sidebar icon in a tinted square, the branded name, and a single line, so About and the sidebar teach the same words. Then give the guidelines a second rhythm: numbered recessed rows, the rule in bold, the explanation in grey.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "support-6",
    surface: "support",
    title: "First run shows three different layouts in its first second",
    evidence: "`<div className=\"mx-auto max-w-[440px] space-y-6 py-10\">` with `{[1, 2, 3, 4, 5].map(...)}` dots and `<div className=\"skeleton-warm mx-auto h-16 w-16 rounded-full\" />` (src/app/(main)/welcome/loading.tsx:3-10). The real flow: `<div className=\"mx-auto flex min-h-[65vh] w-full max-w-[460px] flex-col justify-center py-[var(--space-xl)]\">` with `const dotSteps = STEP_ORDER.slice(0, -1);` (src/components/onboarding/onboarding-flow.tsx:143, :127) and `if (!ready) return null;` (:124).",
    why: "The skeleton is 440px, top-aligned, with a big circle. The real first step is 460px, vertically centred, and has no circle at all; the circle it draws belongs to step five. Between the two the page paints one blank frame. So a brand-new member gets card, blank, card-somewhere-else, jumping about a third of the viewport, on the very first screen of the product.",
    idea: "Extract the wrapper and the dot row into one shell that both the skeleton and the real flow render, so nothing moves between them. Cleanest of all: let Welcome render without the server fetch, and there is no skeleton to get wrong.",
    severity: "looks-broken",
    verified: false,
  },
  {
    id: "support-7",
    surface: "support",
    title: "Step 1 collects nothing, costs a click, and owns a quarter of the progress dots",
    evidence: "`<h1 className=\"font-heading text-[28px] leading-tight tracking-[-0.02em] text-foreground\">Welcome, {firstName}.</h1>` + `Let&apos;s get your page ready so old friends can find you. A few quick steps, and you can skip any of them.` (src/components/onboarding/steps/welcome-step.tsx:24-30). Register/Houses/Photo use `<h2 className=\"font-heading text-[24px] ...\">`, Done uses `text-[26px]`.",
    why: "It is the \"click Next to begin\" screen. It spends one of four dots on no input, and its copy describes the process, which the visible dots and the visible \"Finish later\" link already do. The heading also changes size between steps, 28 then 24 then 26, so the title breathes in and out as you advance.",
    idea: "Either delete it and open on Register with \"Welcome, {firstName}\" as the lead line, or earn it: their own bird at 104px, their first name, and one true sentence such as \"Fourteen people from the Batch of 09 are already here\", which is a single count away. And pin every step heading to one size.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "support-8",
    surface: "support",
    title: "The payoff screen of a product built on fifty birds shows a stock party popper",
    evidence: "`<div className=\"mx-auto grid h-16 w-16 place-items-center rounded-full bg-canopy/10 text-canopy\" aria-hidden><PartyPopper className=\"h-7 w-7\" /></div>` and `Take me to the feed` (src/components/onboarding/steps/done-step.tsx:22-27, :44).",
    why: "One screen earlier the person was told exactly which bird they are and offered to keep it, which is a lovely beat. The finish screen throws that away for clip art in a tinted disc. It is also the highest-intent moment in the product, and the only door out goes to the feed, which for a brand-new account is the emptiest surface there is.",
    idea: "Show them their own bird, the same 104px one from the step before, with one settle spring, so Photo and Done are visibly the same story. Then offer two doors: \"Find my batch\" as the primary, going to the directory filtered to their year, with the feed as the quiet second.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "support-9",
    surface: "support",
    title: "The Houses step turns a fourteen-row chore into one click a year, with a payoff you can see",
    evidence: "`function advanceYear(fromYear: number) { const next = [...rows].sort((a, b) => a.year - b.year).find((r) => r.year > fromYear && r.houses.length === 0); setOpenYear(next ? next.year : null); }` (src/components/onboarding/steps/houses-step.tsx:122-126), plus `Add all my years ({missingRowYears.length})` (:266) and the tinted chain at `className=\"flex flex-wrap items-center justify-center gap-x-1.5 gap-y-2 rounded-2xl border border-border bg-mist/60 p-[var(--space-m)]\"` (:197).",
    why: "Nothing to fix here; it is noted so a refactor does not flatten it. It pre-fills every academic year from dates you already gave, so nobody types a year. It hands the open panel to the next unfilled year, so a whole school career is one click each with no re-aiming. It draws the answer back as a live chain of collapsed same-house runs in per-house tints. And the one-row and empty cases are genuinely handled.",
    idea: "Leave it alone, and borrow from it. The chain preview is what the Done step should copy: show me what I just made. The pre-filled rows are what the Support page should copy: never present an empty container as the answer.",
    severity: "genuinely-good",
    verified: false,
  },
  {
    id: "messages-1",
    surface: "messages",
    title: "The notification panel is the only pure-white surface in the app, and its unread state is invisible",
    evidence: "`--popover: #FFFFFF;` (src/app/globals.css:91) painting `<DropdownMenuContent align=\"end\" className=\"w-80\">` (src/components/layout/notification-bell.tsx:262), with unread rows marked by `${!notif.read ? \"bg-leaf/5\" : \"\"}` (src/components/layout/notification-bell.tsx:293)",
    why: "The popover colour never got warmed with the rest of the palette, so a 320px slab of pure white floats over a warm page and reads as borrowed OS chrome. Worse, unread is carried by leaf at 5% over white, which comes out as a 3% mint wash nobody can see, while the badge on the bell shouts it in cinnamon. People end up re-reading the whole list every time.",
    idea: "Warm the popover token so every dropdown joins the system, and stop encoding unread as a background wash. Give the unread row a 3px cinnamon left edge, the same bar the sidebar already uses for the active nav row, and leave the row's background flat.",
    severity: "looks-broken",
    verified: false,
  },
  {
    id: "messages-2",
    surface: "messages",
    title: "Notifications never got a home: six visible rows, no grouping, and on desktop the bell only exists on the feed",
    evidence: "`take: 20,` (src/app/(main)/notifications/actions.ts:14) feeding `<div className=\"max-h-80 overflow-y-auto\">` (src/components/layout/notification-bell.tsx:276); `unreadCount={unreadCount}` appears in exactly one page, src/app/(main)/feed/page.tsx:53; `src/app/(main)/notifications/` contains only actions.ts, no page.tsx",
    why: "The panel is 320px tall and a row is 52px, so six of the twenty fetched are visible, number 21 is unreachable forever, and there is no notifications page to escape to. Ten people loving one post writes ten rows, because the table has no actor or target to group on, so one popular post evicts everything else. And the bell only mounts where a page opts in, which is the feed alone.",
    idea: "Move the bell into the shell so it exists on every route. Add a real notifications page with day rules and paging, and end the panel with \"See everything\". To group, give the row an actor and a target key, so ten loves become one line with three birds: \"Asha, Ravi and 8 others loved your post\".",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "messages-3",
    surface: "messages",
    title: "The bell's shake, the most carefully commented animation in the file, can never fire",
    evidence: "`const [unreadCount, setUnreadCount] = useState(initialUnreadCount);` (src/components/layout/notification-bell.tsx:97) and `const prevUnread = useRef(initialUnreadCount);` (:103), gated by `if (unreadCount > prevUnread.current) { setShakeKey((k) => k + 1); }` (:106-108)",
    why: "Twenty-nine lines go into it: hand-tuned keyframes, a comment about pivoting from the top, a remount key so it replays. It cannot run. The count is read once at page load, the bell is never remounted, nothing polls or pushes, and the only writer decrements. So the badge quietly goes stale mid-session and the animation built to announce an arrival is dead code. Reopening the panel does not refetch either.",
    idea: "Give the count a source of truth: poll on a slow interval, paused while the tab is hidden, or revalidate on focus. Drop the guard that stops a reopen refetching, and derive the count from the rows instead of a separate counter. Then the shake earns its keyframes.",
    severity: "looks-broken",
    verified: false,
  },
  {
    id: "messages-4",
    surface: "messages",
    title: "A one-message thread prints the same sentence twice, in two type styles, over 104px",
    evidence: "`{threadTitle(t)}` at 15.5px bold (src/components/messages/thread-list.tsx:55-57) sitting directly above `{t.lastFromAdmin ? \"\" : \"You: \"}{previewOf(t.lastBody, 140)}` (src/components/messages/thread-list.tsx:71-74), where the title comes from `subject: deriveSubject(body)` (src/app/(main)/messages/actions.ts:83)",
    why: "The subject is manufactured from the body, so for a thread with one message, which is what everybody sees the instant after they hit Send, the heading and the preview are the same words. Two lines, one fact, 104px of card. The pattern came from mail clients, where subject and body are genuinely different fields. Nobody looked at the one-message case.",
    idea: "Collapse the row when there is only one message: the body once at 15px, clamped to two lines, with the kind glyph and the time on a single meta line. Keep the two-tier treatment for threads that have actually diverged, so the list tells \"sent, waiting\" apart from \"there is a conversation here\".",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "messages-5",
    surface: "messages",
    title: "Conversation bubbles are rounder than the card holding them, and the two speakers are ten RGB points apart",
    evidence: "`className={`mt-1.5 rounded-xl px-3.5 py-3 ${message.fromAdmin ? \"bg-canopy/[0.07]\" : \"bg-mist/70\"}`}` (src/components/messages/conversation.tsx:92-94), nested inside `className=\"card-elevated overflow-hidden rounded-[var(--radius)] border border-border bg-card\"` (src/app/(main)/messages/[id]/page.tsx:81)",
    why: "The bubbles land at 20.8px inside a 16px card, which is the nesting rule inverted: corners that visibly fight. And the two fills that are supposed to tell the speakers apart are both warm greige about ten points apart, neither of them recognisably green. The file's own comment promises the surface does that work. It does none of it, so a six-message thread reads as one grey column.",
    idea: "Take the bubbles to 12px so they nest properly. Then stop asking a wash to carry identity: give the admin side a 2px canopy edge and a stronger fill, or better, leave member messages unfilled on the card and fill only the replies. One filled and one plain is legible at arm's length.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "messages-6",
    surface: "messages",
    title: "No sender grouping, no day rule, and nothing marks what is new since you last looked",
    evidence: "`<ul className=\"flex flex-col gap-5\">` with an unconditional avatar + name + timestamp header on every row (src/components/messages/conversation.tsx:130 and 84-90), while the page silently runs `await prisma.adminThread.updateMany({ where: { id: thread.id, memberId: session.user.id, memberUnread: true }, data: { memberUnread: false } });` (src/app/(main)/messages/[id]/page.tsx:64-67)",
    why: "Three replies in a row draw three avatars, three copies of the name and three timestamps, so a burst reads as three separate incidents. There is no absolute date anywhere until something is a month old. And the page clears your unread flag as it renders, before you have read anything, while drawing nothing to show where the new messages start.",
    idea: "Collapse consecutive messages from one sender inside ten minutes, keeping the avatar on the first and tightening the gap. Add a hairline day rule when the date changes. Capture the last-read time before clearing it, and draw one cinnamon \"New\" rule above the first message after it.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "messages-7",
    surface: "messages",
    title: "Unread is three mechanisms in three colours, and two of them routinely disagree",
    evidence: "`className=\"size-2 rounded-full bg-cinnamon\"` on the thread row (src/components/messages/thread-list.tsx:62), `bg-leaf/5` on the notification row (src/components/layout/notification-bell.tsx:293), and `className=\"flex items-center gap-1 rounded-sm text-xs text-leaf hover:text-leaf-light\"` on Mark all read (src/components/layout/notification-bell.tsx:268)",
    why: "The thread flag and the notification flag are separate booleans with nothing linking them. Open a thread from the user menu and the row's dot clears while the bell still counts it. Press Mark all read and you get the reverse: badge at zero, dots still on the rows. On top of that, one concept is drawn in cinnamon, in a 5% leaf wash, and in a hover green retired everywhere else.",
    idea: "Clear both in the same transaction: when the thread page clears its flag, mark the matching notifications read too. Then settle on one vocabulary, cinnamon for unread everywhere, and make Mark all read a plain muted control, because a utility action does not need an accent colour.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "messages-8",
    surface: "messages",
    title: "The search pill is the most rigorously reasoned control on this surface",
    evidence: "`animate={{ width: open ? OPEN_WIDTH : CLOSED_WIDTH, paddingLeft: open ? OPEN_PADDING_LEFT : 0, paddingRight: open ? 8 : 0 }} transition={open ? OPEN_SPRING : CLOSE_SPRING}` (src/components/layout/search-pill.tsx:97-103), with `OPEN_SPRING = { type: \"spring\", bounce: 0.15, duration: 0.32 }` and `CLOSE_SPRING = { type: \"spring\", bounce: 0, duration: 0.22 }` (:39-43)",
    why: "It refuses Motion's layout animation, because scale plus counter-scale across an eightfold width change reads as stretching, and animates the real values instead. It runs a different spring in each direction, the closing one damped so it cannot overshoot. The icon is deliberately not a motion element, so it can never be skewed. Every constant has its reason written beside it.",
    idea: "Nothing to change, only to reach further: it is hidden below the small breakpoint and mounted on the feed alone, so this excellent control is invisible on mobile and on seven of eight desktop routes. Mount it in the shell, like the bell.",
    severity: "genuinely-good",
    verified: false,
  },
  {
    id: "feed-1",
    surface: "feed",
    title: "A post image is cropped by a fixed pixel height, so a portrait photo shows 39% of itself",
    evidence: "`className={`w-full rounded-xl border border-border object-cover ${images.length === 3 && i === 0 ? \"col-span-2 max-h-64\" : images.length === 1 ? \"max-h-96\" : \"max-h-48\"}`}`, src/components/posts/post-card.tsx:321-327",
    why: "A pixel cap against a fluid width means the crop depends on the window, not the photo. On desktop a 3:2 landscape loses 21% and a portrait shows 39% of itself, a band of torsos out of a group photo. The crop is also final: no click to open, no alt text, no dimensions, so every card below shifts as it loads. The Collection renders the same photographs whole. On a site whose emotional payload is old photographs, the feed is the surface that cuts them up.",
    idea: "Drop the height cap and give the image an aspect box from its stored dimensions, clamped between wide and tall, with anything outside letterboxed on a mist matte so a panorama and a portrait both survive. Make the image open the viewer that already exists, and show the real crop in the composer preview.",
    severity: "looks-broken",
    verified: false,
  },
  {
    id: "feed-2",
    surface: "feed",
    title: "Every notification and share link points at an anchor that does not exist yet",
    evidence: "`const shareHref = `${post.groupId ? `/groups/${post.groupId}` : \"/feed\"}#${post.id}`;`, src/components/posts/post-card.tsx:148, and `link: `/feed#${postId}``, src/app/(main)/feed/actions.ts:306, 390, 411, 793",
    why: "The feed fetches its posts after mount and nothing reads the URL hash, so when the browser goes looking for the post it is not there and it silently gives up. \"Anita commented on your post\" drops you at the top of the feed, and if the post is older than the first twenty it is not on the page at all. That same dead link is what Share copies and what admins click to review a report. A post is the only first-class thing in the product with no page of its own.",
    idea: "Give posts their own route: server-rendered, one-up, comments open, the way a letter reads, and point notifications and Share at it. If that is too much for now, at least read the hash once the first page resolves, fetch the post if it is missing, and ring the card.",
    severity: "looks-broken",
    verified: false,
  },
  {
    id: "feed-3",
    surface: "feed",
    title: "A Letter in the feed gets the full engagement footer for something you have not read",
    evidence: "`<div className=\"mt-2 -mx-2.5 flex items-center gap-1 text-muted-foreground\">` sits outside the isLetter ternary, src/components/posts/post-card.tsx:339, with `<CommentsSection key=\"comments\" postId={post.id} ...>` at :370",
    why: "The card holds a 200-character teaser and then invites you to like it and open a comment thread about it. That also makes two comment surfaces for one letter, and they will diverge, because the people replying from the feed have not read the piece. The Letters page made the opposite call: the whole card is a link and there is no engagement row at all.",
    idea: "Make the feed's letter card one link with no nested box, drop the repeated eyebrow, and cut the footer to Save and Share plus a static \"N replies\" that links through. Keep the heart and the thread for the page where the letter can actually be read.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "feed-4",
    surface: "feed",
    title: "After you vote, the poll row stops being a button, so changing your vote is mouse-only",
    evidence: "`<div key={option.id} onClick={() => handleVote(option.id)} className=\"relative cursor-pointer overflow-hidden rounded-lg border border-border px-4 py-2.5 transition-colors hover:border-leaf/50\">`, src/components/posts/poll-display.tsx:140-143",
    why: "Before the vote it is a real button. After it, a bare div: no role, no keyboard, no pressed state, no announcement when the numbers change. A keyboard or screen-reader user can vote once and then never change it. Sighted users barely fare better, since the only hint the row is still live is a border on hover, and nothing says a vote can be changed at all.",
    idea: "Keep it a button in both states with aria-pressed, and swap only the interior. Add a quiet \"tap again to change your vote\" beside the count that fades after the first change, and put the percentages in a polite live region so the result is announced once, not per row.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "feed-5",
    surface: "feed",
    title: "Two boxes inside the post card are rounder than the card, and a third matches it exactly",
    evidence: "card is `rounded-[var(--radius)]` (16px) at src/components/posts/post-card.tsx:153, images are `rounded-xl` at :321 and the letter block is `mt-3 block rounded-xl border border-border bg-paper/60 p-4` at :234 (--radius-xl = calc(1rem * 1.3) = 20.8px), poll rows are `rounded-lg` at src/components/posts/poll-display.tsx:131,143 (--radius-lg = var(--radius) = 16px)",
    why: "The rule is that a box inside a box never shares its container's radius, and the step should be down. Here the image corners bulge past the card, which reads as a sticker stuck on rather than part of it, and the poll rows land on the card's own radius, so the nesting looks like an accident. The composer's own poll gets this right, two files away, with a comment explaining the rule.",
    idea: "One line each: images and the letter block to 12px, poll rows to 8.8px. Then the card reads 16 outside, 12 for content regions and 8.8 for rows inside them, which is a hierarchy rather than three arbitrary numbers.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "feed-6",
    surface: "feed",
    title: "The right rail is about 999px of sticky content in an 800px viewport",
    evidence: "`<div className=\"sticky top-7 space-y-4\">` wrapping five modules, src/components/feed/feed-rail.tsx:22",
    why: "Add the modules up and the rail is roughly 999px; the visible area at the review size is about 800. Once it pins it never moves again, so the bottom 230px can never be reached however far you scroll. It hides today only because two modules disappear when the data is thin, which means this bug arrives on the day the site is finally alive. Pulse spends 135px and two icon discs to deliver two integers, neither of them clickable.",
    idea: "Either cap the rail and let it scroll inside itself with a fade at the bottom, or keep only the first two modules sticky and let the rest scroll with the page. Separately, fold Pulse's two numbers into one line of text in the rail's footer, so the week's pulse costs 40px rather than 135.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "feed-7",
    surface: "feed",
    title: "A pasted link is dead text everywhere in the product",
    evidence: "`result = result.replace(/@\\[([^\\]]+)\\]\\(([^)]+)\\)/g, '<a href=\"/profile/$2\" class=\"font-semibold text-leaf hover:underline\">@$1</a>'); return result`, src/lib/utils.ts:296-301, consumed by `dangerouslySetInnerHTML={{ __html: renderRichText(...) }}` at src/components/posts/post-card.tsx:267 and src/app/(main)/letters/[id]/page.tsx:130",
    why: "The renderer handles bold, italic and mentions but not URLs, the composer has no link control, and no markdown link is parsed. So there is no path at all from \"here is the reunion form\" to something clickable. Half the reason an alumni network exists is passing things between people. It reads as fine because the URL is visible; it fails the moment anyone tries to use it.",
    idea: "Add an autolink pass after escaping, opening in a new tab with noopener, and shorten the visible label to the host and first path segment. Then, when a post is nothing but a URL, render a real link card in the body slot at the size of an image, so the feed's rhythm holds.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "feed-8",
    surface: "feed",
    title: "The post tag is write-only: five choices that render nowhere and filter nothing",
    evidence: "`const TAGS = [{ value: \"campus-memory\", label: \"Campus Memory\" }, { value: \"life-update\", label: \"Life Update\" }, { value: \"looking-for-connections\", label: \"Looking for Connections\" }, { value: \"photo\", label: \"Photo\" }, { value: \"general\", label: \"General\" }];`, src/components/posts/edit-post-dialog.tsx:15-21",
    why: "The tag goes in and comes back out only to the dialog that set it. It is never shown on a card, and the feed's filters offer only sort and time range. The composer does not offer tags at all, so the only way to tag a post is to publish it and then edit it, to no visible effect. And \"General\" is not a thing anyone would choose on purpose, in a product whose other names are Letters and The Valley Collection.",
    idea: "Decide it in one direction. Either delete the field, or make it real: two or three tags worth filtering by, shown as a small cinnamon pill beside the timestamp and as filter pills under the header, offered in the composer at post time rather than afterwards.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "feed-9",
    surface: "feed",
    title: "The footer row's optical alignment and the three shared buttons are the best-made thing on the card",
    evidence: "`<div className=\"mt-2 -mx-2.5 flex items-center gap-1 text-muted-foreground\">` with the comment \"The negative margin pulls the buttons' padding outward so the heart GLYPH's left edge sits flush with the content's left line ... Touch targets stay full-size; only the padding overhangs\", src/components/posts/post-card.tsx:335-339",
    why: "The negative margins on the row and on the dropdown mean the ink of the heart, the avatar, the text and the share arrow all sit on one line, while every hit target stays over 34px. The buttons match that care: the heart paints red on the first frame with no transition so it can never tween through black, the bookmark pours cinnamon top-down and fires its tug exactly as the fill lands, and share crossfades to a tick with no overshoot. All three animate only transform and opacity.",
    idea: "Only refinement worth trying: hide the literal 0 on the heart and comment counts when a post has no engagement, the way the comment heart already does, so a young feed is not a column of cards each reading 0 0.",
    severity: "genuinely-good",
    verified: false,
  },
  {
    id: "chrome-1",
    surface: "chrome",
    title: "The default secondary-text colour fails AA before anyone even dims it",
    evidence: "`--muted-foreground: #6E7268;` src/app/globals.css:98",
    why: "It measures 4.40:1 on a card and 3.77:1 on the page, where body text needs 4.5. This is the app's colour for everything that is not a headline: 360 uses across 135 files, most of them at 10 to 13px, where the shortfall bites hardest. Nothing looks broken, because it is uniformly a notch too light. The app just looks like it is permanently at 85% brightness.",
    idea: "Move the token to #63675E, or #5E6259 if you want it to clear AA on the page background too. Same warm-grey character, no call-site changes. Then consider a second token for meta text sitting straight on the page, since today it is quietly weaker than the same text inside a card.",
    severity: "looks-broken",
    verified: true,
  },
  {
    id: "chrome-2",
    surface: "chrome",
    title: "Forty text colours are written as an alpha of a token; six land under 2.1:1",
    evidence: "`text-sidebar-foreground/55` src/components/layout/sidebar.tsx:173 (email under the user name) resolves to #91AFA4 on #235C49 = 3.29:1. `text-muted-foreground/45` src/components/profile/houses-chain.tsx:66 resolves to #B9B8AE = 1.78:1. `text-leaf/55` src/components/profile/profile-header-card.tsx:226 resolves to #80B992 = 2.03:1.",
    why: "The worst is the arrow between house pills, effectively invisible at 1.78:1, then the arrows in the Ask, Answer, Read strip at 1.91. The global search placeholder is 2.82. The inactive tab label, everywhere in the app, is 4.08. This is not one mistake, it is a habit: an alpha is one keystroke and nobody checked what colour came out. Over the green sidebar it also leaves the nav labels, the gear, the drawer rows and the hamburger at four different lightnesses with no intent behind the spread.",
    idea: "Ban an alpha on text in the design system and add opaque tokens instead: one idle and one active for the sidebar, one faint one with a floor of 3:1 for genuinely decorative glyphs, and opaque tints for accent text. Then add a lint that fails on the pattern, so it cannot come back.",
    severity: "looks-broken",
    verified: true,
  },
  {
    id: "chrome-3",
    surface: "chrome",
    title: "The app ships 37 font sizes, stepping through the small range in half-pixels",
    evidence: "`sm: \"h-9 gap-1.5 px-3.5 text-[0.8rem] data-[leading-icon]:pl-2.5 data-[trailing-icon]:pr-2.5 [&_svg:not([class*='size-'])]:size-3.5\"` src/components/ui/button.tsx:58",
    why: "Between 10 and 17px it steps 10, 10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15, 15.2, 15.5, 16, 16.5, 17. No two neighbours are distinguishable as intent, so a 12.5 beside a 13 reads as an accident rather than a hierarchy. The shared button's small size is 12.8px, which can never land on a pixel. A six-step scale is written down in globals.css as a comment that no rule enforces.",
    idea: "Turn that comment into real theme entries so the steps become actual utilities, then sweep the 103 fractional call sites onto the nearest one. Start with the button and the sidebar, which between them cover the two most-seen controls. Cap the product at eight sizes: if something needs 13.5, then 13 or 14 was already right.",
    severity: "looks-broken",
    verified: true,
  },
  {
    id: "chrome-4",
    surface: "chrome",
    title: "Icon outlines are drawn at five different thicknesses, none of them a whole pixel",
    evidence: "`<n.icon className=\"relative z-[2] h-[18px] w-[18px] shrink-0\" strokeWidth={1.9} />` src/components/layout/sidebar.tsx:148-151",
    why: "Lucide scales the stroke with the box, so 1.9 in an 18px box is 1.425 CSS px: split across three physical pixel columns and never crisp. The chrome alone draws at 1.425, 1.504, 1.667, 1.742 and 0.950. The mobile and desktop bells differ by 5.5% for no reason, and the drawer's close X is heavier than every row beneath it. Both bells then carry a half-pixel nudge, which on a 1x screen just blurs the glyph. It does not read as broken, it reads as the icons being slightly soft.",
    idea: "Pick one stroke of 2 and one box ladder that divides cleanly by 24: an 18px box then gives exactly 1.5 CSS px. Export a nav-icon wrapper so no call site passes a stroke by hand, set the two bells to one size, and replace the half-pixel nudges with a whole pixel or a corrected viewBox.",
    severity: "looks-broken",
    verified: true,
  },
  {
    id: "chrome-5",
    surface: "chrome",
    title: "Three card radii in one product, and post cards nest boxes rounder than the card",
    evidence: "`\"group/card card-elevated flex flex-col gap-4 overflow-hidden rounded-xl border border-border bg-card pt-4 pb-5 ...\"` src/components/ui/card.tsx:15",
    why: "The scale is defined as multiples of 1rem, so four of its seven steps land on fractions and the corner arc never ends on a pixel. The shared Card is 20.8px while the spec says 16 and 87 hand-rolled cards use 16. Inside the most-seen component in the app, the image and the link preview are 20.8px inside a 16px card, so the child corner bulges out of its parent. There are 23 distinct card shapes across 149 uses, including four flat shadows the rules explicitly forbid.",
    idea: "Redefine the scale on whole pixels: 8, 12, 16, 20, 24. Point the Card primitive at 16. Set every box nested inside a 16px card to 12, which fixes both post-card offenders and gives the nesting rule one answer instead of a per-author guess.",
    severity: "looks-broken",
    verified: true,
  },
  {
    id: "chrome-6",
    surface: "chrome",
    title: "One role, six title sizes, two weights: /feed and /settings render the same 30px title in different faces",
    evidence: "`<h1 className=\"font-heading text-[30px] leading-none tracking-[-0.02em] text-foreground\">` src/components/layout/page-header.tsx:37 versus `<h1 className=\"font-heading text-3xl font-bold text-foreground\">` src/app/(main)/settings/page.tsx:48",
    why: "Preflight resets heading weight to inherit, so the shared header renders regular while every hand-rolled title is bold. Both faces are loaded, so this is a real visible difference: clicking down the sidebar toggles the masthead's weight. The full inventory of the page-title role is six sizes and three trackings. One page even re-types the shared header's classes character for character instead of importing it, so the one place that did match is a copy that will drift.",
    idea: "Make the shared header mandatory, with a smaller size for detail pages, and decide the weight once. Regular at 30px is the more distinctive choice for a warm editorial product; bold is the default-looking one. Route the six hand-rolled titles through it, which also gets them the action slot only two of fourteen headers use today.",
    severity: "looks-broken",
    verified: true,
  },
  {
    id: "chrome-7",
    surface: "chrome",
    title: "Six reading widths mean the page title slides 224px right as you click down the sidebar",
    evidence: "`<main className=\"mx-auto w-full max-w-[1280px] flex-1 px-5 py-6 sm:px-7 lg:px-10 lg:py-8\">` src/components/layout/app-shell.tsx:48, against per-route caps `max-w-2xl` (messages), `max-w-3xl` (letters, settings, about, support), `max-w-4xl` (groups), `max-w-5xl` (directory, collection, admin), `max-w-[680px]` (letters/[id])",
    why: "Each route centres a different cap inside the same space, so the title's left edge lands at five different positions. Nothing about the content justifies it; they were each sized in isolation. The most stable element on the screen ends up being the one thing that never sits still. The shell's two branches also use different gutters, so the baseline shifts 4px vertically too, and the rail branch meant to unify all this is dead code no page ever calls.",
    idea: "Define three named measures as tokens, one for reading, one for lists, one for grids, and let each route pick one. Anchor the title to the left edge of the content area rather than to the centred column, so it holds one position everywhere. Then either wire the rail prop up or delete it and export the grid as a component.",
    severity: "looks-fine-but-thoughtless",
    verified: true,
  },
  {
    id: "chrome-8",
    surface: "chrome",
    title: "The skeletons were drawn from memory: the feed's has no header, and its cards are the wrong shape",
    evidence: "`<div key={i} className=\"rounded-xl border border-border bg-card p-6\">` src/app/(main)/feed/loading.tsx:11, against the real card `\"card-elevated rounded-[var(--radius)] border border-border bg-card p-4\"` src/components/posts/post-card.tsx:153",
    why: "The feed's real header is about 64px of title, search, bell and CTA. Its skeleton has none of it, so all of that appears out of nowhere and shoves the feed down at the moment the eye has settled. The skeleton card is 20.8px and p-6 against a real 16px and p-4, so every card re-corners and re-pads on swap. Same in directory, groups, settings and profile. One message header uses a flat white bar instead of the warm shimmer, so it sits dead still while everything below it moves.",
    idea: "Extract a skeleton card and a skeleton header that read the same tokens the real components read, so the two can never drift. Give the shared header a loading variant so the feed reserves its exact box, and let the shimmer take a surface, so nothing has to fall back to a static bar.",
    severity: "looks-fine-but-thoughtless",
    verified: true,
  },
  {
    id: "chrome-9",
    surface: "chrome",
    title: "The Button's automatic per-side optical padding is the best-considered thing in the token layer",
    evidence: "`default: \"h-10 gap-2 px-4 data-[leading-icon]:pl-3 data-[trailing-icon]:pr-3\"` src/components/ui/button.tsx:55-56, driven by `detectIconSides` at src/components/ui/button.tsx:94-107",
    why: "An icon carries less ink than its box, so symmetric padding reads looser on the icon side. Most systems ignore that, or make every call site pass a one-off. This one works out at runtime whether the first or last child is an icon, handles both the client case and the server case where the icon has already become a raw svg, refuses to shift an icon-only button, and applies the correction through data attributes so the CSS stays declarative. The comment explains why the obvious CSS cannot do the job.",
    idea: "Nothing to change. If anything, spread it: the small and large sizes already carry proportional corrections, so give chips and tags the same treatment instead of padding symmetrically around their icons.",
    severity: "genuinely-good",
    verified: true,
  },
  {
    id: "catchups-1",
    surface: "catchups",
    title: "Every group gets the same 104px tile, so a live Round and one that never started look identical",
    evidence: "src/app/(main)/catchups/page.tsx:256 `{data.cards.map((card) => (<YourCatchupsCard key={card.groupId} card={card} />))}` feeding the single unconditional shell at src/components/catchups/index/your-catchups-card.tsx:41 `className=\"card-elevated group flex flex-col gap-[var(--space-m)] rounded-[var(--radius)] border border-border bg-card p-[var(--space-m)] transition-colors duration-150 hover:border-canopy/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/50 active:border-canopy/60 sm:flex-row sm:items-center sm:justify-between\"`",
    why: "Five tiles, 574px of column. Three of them say \"No Catch-up here yet\" and carry exactly the weight of the two with a published issue. Across the whole eight-state machine the only things that change are the button label and one text colour. So the page spends its entire budget saying \"here are your groups\", which another page already said, and says nothing about where anything is in its cycle.",
    idea: "Stop mapping memberships one to one. Give the Round that actually needs you a full-weight block; let published Rounds drop out of the column, since the rail already carries them better; and collapse every never-started group into a single row of \"Start one in ...\" chips. Five tiles becomes one block and a 40px row.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "catchups-2",
    surface: "catchups",
    title: "The 318px rail carries more about a Round than the 764px tile beside it",
    evidence: "src/app/(main)/catchups/page.tsx:185-199 `where: { status: \"published\", catchup: { group: { members: { some: { userId } } } } }` (the rail) against page.tsx:39-43 `case \"published\": return { label: \"Read the Round\", href: editionId ? ... }` (the tile), with no de-duplication between them",
    why: "The left tile says the group name, \"Round 1 published\", and a button. The rail row, a quarter of the width, says the Round number, the group, the publish date, a quoted line from the most-loved answer, and how many people wrote in. The bigger, louder element is the poorer rendering of the same object. Nobody put the two side by side and asked which one wins.",
    idea: "Make the two lists disjoint. The left column owns Rounds that want something from you; the rail owns Rounds that are finished reading. A Round leaves the column the moment it publishes, which is also the right emotional handoff: it stops being a task and becomes an archive.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "catchups-3",
    surface: "catchups",
    title: "A paused Catch-up prints the word \"Paused\" in publish-green",
    evidence: "src/components/catchups/index/your-catchups-card.tsx:14-20 `const STATUS_TONE: Partial<Record<EditionStatus, string>> = { collecting: \"text-leaf\", answering: \"text-cinnamon\", preparing: \"text-muted-foreground\", published: \"text-canopy\", draft: \"text-muted-foreground\" };` read at line 34 `const tone = card.editionStatus ? (STATUS_TONE[card.editionStatus] ?? \"text-muted-foreground\") : \"text-muted-foreground\";`",
    why: "The colour is keyed off the Round while the words are keyed off the Catch-up, so pausing one whose last Round published gives you \"Paused\" in the exact green every finished, successful Round wears. Separately, \"preparing\", which is the feature's designed emotional peak, and \"draft\", where nothing has ever happened, share one grey. The colour map has five keys for an eight-state machine.",
    idea: "Derive the tone from the same resolved value the words come from: one function returning a label and a tone for all eight cases. Give paused and ended a genuinely dormant treatment rather than just another colour, and give preparing the cinnamon it deserves, with the hours to reveal in the line.",
    severity: "looks-broken",
    verified: false,
  },
  {
    id: "catchups-4",
    surface: "catchups",
    title: "Four segmented pills in one feature, and the two that set the same field look nothing alike",
    evidence: "src/components/catchups/create/cadence-control.tsx:63 `className=\"absolute inset-0 rounded-full bg-canopy shadow-[0_5px_13px_-12px_var(--color-canopy)]\"` (track `bg-muted/70`, white text) versus src/components/catchups/home/keeper-settings-dialog.tsx:125 `className=\"absolute inset-0 z-0 rounded-full border border-canopy bg-canopy/10\"` (track `bg-muted/40`, canopy text) - both are Biweekly / Monthly / Quarterly. Third variant at src/components/catchups/home/reminder-pref-control.tsx:72; fourth at src/components/catchups/home/console-collecting.tsx:150-155 `showAsker === opt.value ? \"bg-canopy text-white\" : \"text-muted-foreground hover:text-foreground\"` with `transition-colors` and no `layoutId`.",
    why: "Choosing the cadence when you create a Catch-up gives a solid canopy thumb with white text. Changing that same cadence a week later gives a hollow outline with canopy text. Same field, same three labels, two controls, so the settings dialog does not read as the thing you chose earlier. Three of the four glide their thumb; the one with a privacy consequence, ask as yourself or anonymously, just snaps.",
    idea: "Extract one segmented-pill primitive with one thumb, one track and the glide always on, then use it in all four places. Take the outline thumb: it survives on the rail and inside a dialog, while a solid canopy fill is a CTA colour and reads as a button in a row of buttons.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "catchups-5",
    surface: "catchups",
    title: "One feature, four date formats, and the same row built twice under two names",
    evidence: "src/components/catchups/edition/masthead.tsx:47 `toLocaleDateString(\"en-GB\", { day: \"numeric\", month: \"long\", year: \"numeric\" })`; src/components/catchups/home/console-published.tsx:33 `toLocaleDateString(\"en-IN\", { day: \"numeric\", month: \"long\", year: \"numeric\" })`; src/components/catchups/home/archive-shelf.tsx:21 `toLocaleDateString(\"en-IN\", { day: \"numeric\", month: \"short\", year: \"numeric\" })`; src/components/catchups/index/fresh-off-the-press.tsx:22 `toLocaleDateString(\"en-US\", { month: \"short\", day: \"numeric\" })`",
    why: "The masthead says \"25 July 2026\", the rail two inches away says \"25 Jul 2026\", and the index says \"Jul 25\" with the year dropped, which goes wrong the moment the archive spans a year. One component says \"N people wrote in\" and the other says \"N wrote in\" for the identical fact. They render the same object, a published Round, under two headings. Two people built the same row and neither reconciled it.",
    idea: "One date formatter, one locale, and one shared Round row used by both the archive and Fresh off the press, the only difference being whether the group name prints: needed on the cross-group index, redundant on a single group's home.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "catchups-6",
    surface: "catchups",
    title: "The reveal moment is literally the same component as the \"database not migrated\" error",
    evidence: "src/components/catchups/home/catchup-home-shell.tsx:66-70 `<AlmostReady eyebrow={`Round ${edition.number}`} title=\"Putting your Catch-up together.\" body=\"No one can read the answers yet, not even the Keeper...\" />` rendering src/components/catchups/almost-ready.tsx:103 `<div className=\"skeleton-warm h-3 w-24 rounded-full\" />` ... `<div className=\"skeleton-warm mt-2.5 h-3 w-full rounded-md\" />`; `publishAt` is loaded at src/app/(main)/catchups/[catchupId]/page.tsx:349 and typed at src/components/catchups/home/types.ts:54 but grep finds no component that renders it",
    why: "AlmostReady's own comment says it exists for the case where the tables do not exist yet. So the meaning of that shimmering fake card is \"our backend is broken\", and it is reused unchanged for the 24-hour hold that is supposed to be the payoff of the whole cycle. The page knows the question count, who wrote in, and the exact publish time, and shows none of it. The one place a countdown would genuinely mean something is the one place there is not one.",
    idea: "Give preparing its own scene: a sealed envelope, not a loading skeleton. Show the facts the reveal is made of, the questions as closed unreadable rows, and one clear \"Opens in 18 hours\" off the real timestamp, with the hoopoe beside it. Keep the shimmer for the genuine error, so a shimmer never means two different things.",
    severity: "looks-fine-but-thoughtless",
    verified: false,
  },
  {
    id: "catchups-7",
    surface: "catchups",
    title: "Hovering the dimmed avatars names exactly the people the design was careful not to name",
    evidence: "src/components/catchups/home/member-strip.tsx:41-46 `className={cn(\"rounded-full ring-2 ring-card transition-opacity duration-150\", dim && \"opacity-40 grayscale-[0.4]\")}` with `title={m.name}` on the same element; the file header at lines 6-9 says \"members who have not yet answered are dimmed, never named or singled out (spec 3.6 'do not shame non-answerers')\"",
    why: "While a Round is answering, the strip greys out everyone who has not written in, which is a fine ambient signal. But every avatar carries a title attribute, so hovering the greyed ones produces a name-by-name list of who is holding the group up. The dimming existed to give a count without an accusation. And the attribute is not even an accessibility win: it is invisible to keyboard users and unreliable to screen readers.",
    idea: "Drop the title from the dimmed avatars, and keep it, or better a real aria-label, only on the ones who have written in. Give the strip one aria-label carrying the count, \"6 of 12 have shared\", so assistive tech gets the number rather than the roster.",
    severity: "looks-broken",
    verified: false,
  },
  {
    id: "catchups-8",
    surface: "catchups",
    title: "The published Round's table of contents is three deliberate decisions in forty lines",
    evidence: "src/components/catchups/edition/toc.tsx:57 `{ rootMargin: \"-96px 0px -55% 0px\", threshold: [0, 1] }` with the tiebreak at line 50 `if (top <= 160 && top > bestTop)`, and the marker at line 90 `transition={NAV_MARKER_SPRING}` animating `animate={{ y: marker.y }}` off a measured `offsetTop`",
    why: "Do not touch it. One scroll-spy hook feeds two different shapes, a sticky rail on desktop and a chip row on mobile, instead of forking into two. The margin plus a tiebreak means the highlighted item is the section you are actually reading, not merely the topmost one on screen, which almost every table of contents gets wrong. And the marker moves on a measured offset using the sidebar's own spring rather than Framer's layout prop, which this repo has been bitten by before.",
    idea: "Promote the hook and the marker rail into a shared primitive, so the Letters reader and any future long-form page inherit the same in-page navigation instead of solving scroll-spy all over again.",
    severity: "genuinely-good",
    verified: false,
  },
];
