# Canonical deduped findings. Each maps to constituent W1 raw IDs.
# severity, title authored by orchestrator; primary = W1 id whose evidence is richest.
CANON = [
 # ---------- CRITICAL ----------
 ("B-001","Critical","Deleting/purging a Group creator cascade-destroys the whole group, its posts, and any Catch-up with every member's answers",
   "W1-057",["W1-057","W1-148","W1-309","W1-058"],
   "Group.creator onDelete:Cascade + Catchup/Post/GroupMember cascades. First batch member and Catch-up initiator become creatorId. Self-delete->retention purge fires prisma.user.delete -> full cascade. Contradicts Catchup.createdById SetNull comment 'nullable so the Catch-up survives if they leave'. ORCHESTRATOR-VERIFIED in code (joinBatchGroup creatorId=first member; createCatchupWithPeople creatorId=initiator)."),
 ("B-002","Critical","A transient Resend failure permanently fails a queued email: all attempts burn in one drain pass, no backoff, no transient/permanent split",
   "W1-262",["W1-262","W1-089"],
   "drainMailQueue loop re-picks the same requeued row immediately, burning MAX_ATTEMPTS back-to-back; claimAndSend has no transient vs permanent distinction. A 30s Resend brownout permanently fails every in-flight verify/reset."),
 # ---------- HIGH: data-integrity / cascade ----------
 ("B-010","High","Deleting a member cascades away every Catch-up question they asked, removing every OTHER member's answers to it from published Rounds",
   "W1-058",["W1-058"],
   "CatchupPrompt.author onDelete:Cascade and CatchupEntry.prompt Cascade: purging a question's author deletes the prompt and all entries under it."),
 ("B-011","High","Account purge deletes DB rows first then R2 bytes best-effort from an in-memory URL list; any crash/timeout mid-loop permanently orphans images",
   "W1-310",["W1-310","W1-161","W1-259"],
   "purgeUserAccount: prisma.$transaction deletes rows, then for-loop delImage over urls collected before the delete. No resume, no persisted worklist. Unbounded sequential R2 deletes vs Vercel duration ceiling."),
 ("B-012","High","Account purge and the 2-year sweep never delete AdminMessage.imageUrl screenshots or Group.coverImage from R2 — permanent orphans / GDPR gap",
   "W1-278",["W1-278","W1-311"],
   "collectImageUrls omits AdminMessage.imageUrl and Group.coverImage; no path ever deletes them."),
 ("B-013","High","R2 delete failures are swallowed with no log (delImageByKey empty catch) and purge counts delete ATTEMPTS as deletions — the audit line lies",
   "W1-171",["W1-171","W1-147"],
   "storage.ts delImageByKey catch{} empty; purgeUserAccount increments deleted per attempt regardless of success."),
 # ---------- HIGH: auth / account ----------
 ("B-020","High","Email case/whitespace normalized inconsistently: mixed-case accounts can never reset password, false login failures, one mailbox registers twice",
   "W1-034",["W1-034","W1-091","W1-169","W1-231","W1-264","W1-331"],
   "LIVE-CONFIRMED: 1 of 52 members has mixed-case email today (cannot reset). authorize() looks up raw email; reset lowercases; signup stores/dedupes raw. Backfill safe (0 dup-lower pairs)."),
 ("B-021","High","Verification link superseded by any resend shows 'Already confirmed - nothing left to do' (happy bird, no resend button) to a still-unverified member",
   "W1-150",["W1-150","W1-170"],
   "confirmEmailToken treats a used/expired-superseded token as already-confirmed; member is NOT verified, sees a dead-end success screen."),
 ("B-022","High","proxy.ts redirects signed-out visitors to /login?callbackUrl=<path> but the login page reads only ?next= — every shared deep link drops to /feed",
   "W1-332",["W1-332"],
   "proxy sets callbackUrl; login-client + next-path.ts read next=. Deep links (shared post/letter/profile) never return to target after login."),
 ("B-023","High","An admin can block or delete their own or the last admin's account with no guard — permanent lockout of the whole admin surface",
   "W1-001",["W1-001"],
   "admin-actions block/delete lack a last-admin / self guard (adminSetRole has a check-then-act one, block/delete none)."),
 ("B-024","High","All 12 /admin pages rely on the layout gate, which does not re-run on page-segment RSC requests: a demoted admin keeps reading admin data mid-session",
   "W1-123",["W1-123"],
   "SUSPECTED: admin/layout.tsx is the only role gate; RSC segment requests may skip layout re-eval. Needs live proof."),
 # ---------- HIGH: uploads / Vercel ----------
 ("B-030","High","Onboarding + settings avatar and Catch-up answer photos ship raw bytes (up to 15MB / 5MBx3) through Server Actions past Vercel's ~4.5MB body cap",
   "W1-035",["W1-035","W1-159","W1-160","W1-333"],
   "photo-step ships raw file to updateAvatar; catchup answer allows 5MBx3 to /api/upload; both exceed 4.5MB -> 413 before the function runs, opaque failure at first-run."),
 # ---------- HIGH: feed / posts / letters ----------
 ("B-040","High","All five like/vote/bookmark toggle actions are check-then-write with no P2002/P2025 handling: a double-tap throws a raw error and desyncs the UI",
   "W1-151",["W1-151","W1-209","W1-210"],
   "toggleLike/toggleCommentLike/toggleBookmark/togglePhotoLove/votePoll: find-then-create, unhandled unique/notfound; no client rejection handler."),
 ("B-041","High","Deleting or editing a post from the feed never updates the on-screen list: the stale/old card stays until a full reload",
   "W1-296",["W1-296","W1-208"],
   "post-feed client posts state has no removal/update path after delete/edit server action."),
 ("B-042","High","No client component handles a rejected server action anywhere: one network blip / deploy skew / auth redirect strands the UI (infinite skeletons, stuck buttons)",
   "W1-298",["W1-298","W1-090"],
   "Systemic: fetch/mutation handlers lack try/catch across feed, collection, profile, notifications, auth."),
 ("B-043","High","Letter autosave fails silently: on any error the desk keeps saying 'Saving...', and a fresh never-saved letter is lost entirely on nav/close/crash",
   "W1-092",["W1-092","W1-297"],
   "autosave error path leaves 'Saving...' with no surface; no draft persistence for an unsaved letter/long post."),
 ("B-044","High","Composer Post/Save stays enabled while photo uploads are in flight: the post publishes without its photos",
   "W1-299",["W1-299"],
   "create-post-form submit not gated on in-flight upload promises."),
 ("B-045","High","'This week in Letters' rail surfaces city-scoped letters to every member sitewide — content leak + guaranteed 404 on click-through",
   "W1-245",["W1-245"],
   "letters-module rail query omits the cityScope visibility filter the letter page enforces."),
 ("B-046","High","Like/comment/reply notifications link to /feed#<postId> (never scrolls, wrong for group posts/letters); admin bell links to retired /admin?thread=",
   "W1-246",["W1-246","W1-247"],
   "notification link builders use #fragment and a removed admin route."),
 ("B-047","High","editPost caps plain posts at 5000 chars while createPost accepts 20000 — a legitimately long post becomes permanently uneditable",
   "W1-212",["W1-212"],
   "editPost validator maxes 5000; createPost 20000."),
 ("B-048","High","A letter draft's city audience is invisible and unchangeable at the desk: editPost drops cityScope and the desk never hydrates it",
   "W1-248",["W1-248"],
   "editPost omits cityScope from the update; edit page does not load it."),
 ("B-049","High","Contact-editor stale closure: removing a phone/link/email row saves the PRE-removal list, so the removed value silently survives",
   "W1-276",["W1-276"],
   "commitContacts reads a stale contactRows closure captured before the removal setState."),
 ("B-050","High","A member cannot remove their profile email: clearing it saves displayEmail=null and the page then falls back to exposing the private sign-in email",
   "W1-277",["W1-277"],
   "profile page falls back to user.email when displayEmail is null."),
 # ---------- HIGH: catch-ups lifecycle ----------
 ("B-060","High","A Catch-up whose Round publishes while paused never schedules another Round; resume does not re-arm nextOpensAt and there is no manual recovery",
   "W1-045",["W1-045"],""),
 ("B-061","High","Pausing or ending a Catch-up does not stop the in-flight Round: it keeps advancing, sending daily reminders, and publishes itself",
   "W1-059",["W1-059"],""),
 ("B-062","High","A Catch-up nobody adds questions to still runs the full cycle: answering opens with zero questions and everyone is reminded to answer nothing",
   "W1-060",["W1-060"],""),
 ("B-063","High","Enrolment is unilateral and irreversible: a Keeper can add anyone, who then gets cycle notifications forever with no way to leave",
   "W1-061",["W1-061"],""),
 # ---------- HIGH: email pipeline ----------
 ("B-070","High","deletion-scheduled emails can never be sent: drain eligibleKinds omits the kind, so every account-deletion confirmation / takeover alarm sits queued forever",
   "W1-263",["W1-263","W1-122"],
   "ORCHESTRATOR-VERIFIED: MailKind includes 'deletion-scheduled' but eligibleKinds is always ['verify','reset','password-changed']."),
 ("B-071","High","A bounce/complaint webhook flips a 'sent' row to 'failed', which resurrects daily-budget slots and lets the app send past Resend's real 100/day cap",
   "W1-265",["W1-265","W1-152"],
   "dailyBudget counts by status; webhook status='failed' on a delivered row frees a slot."),
 ("B-072","High","Drain concurrency is unbounded: every authenticated page view and every enqueue kicks a full drain, so launch traffic fans past Resend's rate",
   "W1-266",["W1-266"],""),
 # ---------- HIGH: money ----------
 ("B-080","High","Payment success callback has no error handling: a thrown confirmContribution after money moved leaves the button stuck on 'Opening' forever, no receipt",
   "W1-345",["W1-345"],""),
 ("B-081","High","When the webhook (not the browser) records a payment, the supporter gets nothing: no notification, no email, no path to the promised bird perk",
   "W1-346",["W1-346"],""),
 # ---------- HIGH: scale / perf ----------
 ("B-090","High","Missing indexes on hot count FKs: Like.postId, Comment.parentId, PollVote.postId/pollOptionId, CommentLike.commentId, PhotoLove.photoId, Post.authorId",
   "W1-134",["W1-134","W1-135"],
   "Uniques lead with userId so per-target counts seq-scan; Comment.parentId thread reads full-scan; Post.authorId profile reads full-scan. See CL-13 dossier."),
 ("B-091","High","Place gazetteer search full-scans all 234,934 rows on every keystroke of 4+ chars: the altNames ILIKE arm in an OR defeats the expression index",
   "W1-103",["W1-103"],""),
 ("B-092","High","Directory page serializes every located member into map props on every load and every filter change (~1-2MB) with no take/pagination",
   "W1-136",["W1-136"],""),
 ("B-093","High","Visit and SearchLog (identifiable presence telemetry) have no retention: absent from the sweep, prune.mjs, and the retention table — unbounded growth",
   "W1-312",["W1-312"],""),
 ("B-094","High","Supabase Free plan cannot carry 2,000 members: egress alone lands multiples over the 5GB/month cap (per-request session findUnique + full-member directory)",
   "W1-104",["W1-104"],
   "SUSPECTED/infra: depends on plan tier. Quantify in dossier."),
 # ---------- HIGH: dates ----------
 ("B-100","High","Every server-rendered date shows the UTC calendar day, not IST: anything timestamped 00:00-05:30 IST renders one day early, sitewide",
   "W1-322",["W1-322","W1-023"],
   "formatDisplayDate/formatTimeAgo have no timeZone. Umbrella; per-surface instances in dates dossier."),
 ("B-101","High","Admin analytics Rhythms heatmap applies AT TIME ZONE 'Asia/Kolkata' in the wrong direction, shifting every hour bucket by ~11 hours",
   "W1-002",["W1-002","W1-109"],
   "Double-conversion / wrong direction on a timestamp-without-tz column."),
 # ---------- HIGH: validation ----------
 ("B-110","High","Onboarding updateProfile action validates nothing: seven profile columns writable with no length caps up to the 25MB action limit",
   "W1-232",["W1-232"],""),
 ("B-111","High","updateUserPlaces and adminUpdatePlaces have no schema: unbounded label/city strings and lat/lng, FK crash on bogus placeId",
   "W1-233",["W1-233"],""),
 # ---------- HIGH: bell / concurrency ----------
 ("B-120","High","The notification bell badge is frozen for the whole browsing session: (main) layout computes unreadCount only on hard loads; badge only ever falls",
   "W1-124",["W1-124"],""),
 ("B-121","High","joinBatchGroup is check-then-create with no unique on Group.name: concurrent same-batch signups (launch day) create duplicate 'Batch of Y' groups, splitting the batch",
   "W1-149",["W1-149"],
   "LIVE: 0 dup groups today (latent). Race needs concurrency; launch is the spike."),
 ("B-122","High","'Most loved' collection sort has no deterministic tiebreaker: offset pagination duplicates and drops photos, and produces duplicate React keys",
   "W1-076",["W1-076"],""),
]
if __name__=="__main__":
    import json
    print(len(CANON),"canonical findings")
    from collections import Counter
    print(dict(Counter(c[1] for c in CANON)))
