/* ------------------------------------------------------------------ *
 *  The invented population of the demo database.
 *
 *  EVERY person here is fictional. No name, email, employer or city is
 *  taken from a real member, and the sign-in addresses all sit on the
 *  `.invalid` TLD, which IETF reserves precisely so it can never resolve
 *  (RFC 2606). That is deliberate: the demo is a public link, and the one
 *  thing it must never do is publish somebody's real life.
 *
 *  What IS real is the texture. Batches run from 1971 to 2024 so the
 *  directory's decade filters have something to bite on, cities are all
 *  keys the map gazetteer (src/lib/city-coords.ts) can place so no pin
 *  falls in the sea, and houses come from the canonical 22 in
 *  src/lib/houses.ts. A demo that looks plausible is doing its job; a
 *  demo that looks generated is not.
 *
 *  Birds are NOT set here. Every avatar is hashed from the user id
 *  (src/lib/avatar.ts), so varied slugs give a varied aviary for free,
 *  and the one thing a visitor is most likely to notice first is the
 *  thing we did not have to hand-author.
 * ------------------------------------------------------------------ */

export interface DemoPerson {
  /** Stable id fragment. Also the seed the bird avatar hashes from, so
   *  changing one re-rolls that person's species. */
  slug: string;
  name: string;
  accountType?: "alumnus" | "teacher" | "ex_teacher";
  batchYear?: number;
  batchType?: "ISC" | "ICSE";
  yearJoined?: number;
  gradeJoined?: number;
  /** Must be a key in CITY_COORDS so the directory map can place a pin. */
  city: string;
  secondCity?: string;
  jobTitle?: string;
  workplace?: string;
  /** One line, shown under the name on cards. */
  bio?: string;
  /** The profile's "in their words" paragraph. */
  about?: string;
  /** One house per year from yearJoined onward; the seeder pairs them up. */
  houses?: string[];
  subjects?: string;
  taughtFrom?: number;
  taughtUntil?: number | null;
}

/** The persona every demo visitor arrives as. Kept first, and kept ordinary:
 *  a plausible mid-career alumna whose profile is filled in enough that the
 *  sidebar, her own profile page and the Catch-up all look lived in from the
 *  first second, without her being the loudest person in the room. */
const DEMO_VISITOR: DemoPerson = {
  slug: "visitor",
  name: "Meera Sundaram",
  batchYear: 2011,
  batchType: "ISC",
  yearJoined: 2004,
  gradeJoined: 5,
  city: "bengaluru",
  jobTitle: "Architect",
  workplace: "Studio Kamal",
  bio: "Draws buildings that try to sit lightly on the ground.",
  about:
    "Eight years in the valley, and I am fairly sure the reason I became an architect is that I spent my childhood in buildings that knew exactly how to be quiet. I work in Bengaluru now, mostly on schools and small libraries. If you are passing through, the coffee is good and the guest room is free.",
  houses: ["Neem", "Neem", "Raavi", "Malli", "Malli", "Gulmohar", "Gulmohar", "Amaltash"],
};

const DEMO_PEOPLE: DemoPerson[] = [
  // ── The oldest batches: the directory needs real depth at the top ──
  {
    slug: "rukmini-iyer",
    name: "Rukmini Iyer",
    batchYear: 1971,
    batchType: "ISC",
    yearJoined: 1964,
    gradeJoined: 5,
    city: "chennai",
    jobTitle: "Retired Paediatrician",
    bio: "Fifty years of other people's children, and still counting.",
    about:
      "I arrived in the valley the year the new dining hall opened and left knowing how to identify forty birds by call. One of those skills paid the bills. The other one turned out to matter more.",
    houses: ["Golden", "Golden", "Silver", "Silver", "Neem", "Neem", "Palm", "Palm"],
  },
  {
    slug: "krishnan-menon",
    name: "Krishnan Menon",
    batchYear: 1974,
    batchType: "ISC",
    yearJoined: 1968,
    gradeJoined: 6,
    city: "kochi",
    jobTitle: "Retired Civil Engineer",
    bio: "Built bridges. Prefers footpaths.",
    houses: ["Raavi", "Raavi", "Trishul", "Trishul", "Kailash", "Kailash", "Meru"],
  },
  {
    slug: "sarojini-bhatt",
    name: "Sarojini Bhatt",
    batchYear: 1978,
    batchType: "ISC",
    yearJoined: 1971,
    gradeJoined: 5,
    city: "pune",
    jobTitle: "Potter",
    workplace: "Kumbha Studio",
    bio: "Makes bowls. Teaches anyone who asks.",
    about:
      "I did not touch clay until I was forty. The valley gave me the patience for it thirty years earlier and then waited, very quietly, for me to notice.",
    houses: ["Malli", "Malli", "Krishna", "Krishna", "Cauvery", "Cauvery", "Amaltash", "Amaltash"],
  },
  {
    slug: "anand-rao",
    name: "Anand Rao",
    batchYear: 1982,
    batchType: "ISC",
    yearJoined: 1975,
    gradeJoined: 5,
    city: "london",
    secondCity: "bengaluru",
    jobTitle: "Documentary Editor",
    workplace: "Farthing Films",
    bio: "Cuts other people's films. Owns too many hard drives.",
    houses: ["Green", "Green", "Red", "Red", "White", "White", "Blue", "Blue"],
  },
  {
    slug: "fatima-sheikh",
    name: "Fatima Sheikh",
    batchYear: 1985,
    batchType: "ISC",
    yearJoined: 1979,
    gradeJoined: 6,
    city: "hyderabad",
    jobTitle: "High Court Advocate",
    bio: "Argues for a living. Was trained for it at the debating table.",
    houses: ["Nilgiri", "Nilgiri", "Meru", "Meru", "Trishul", "Trishul", "Kailash"],
  },
  {
    slug: "vikram-desai",
    name: "Vikram Desai",
    batchYear: 1988,
    batchType: "ISC",
    yearJoined: 1981,
    gradeJoined: 5,
    city: "mumbai",
    jobTitle: "Cinematographer",
    bio: "Chasing the same light I first saw from Rishi Konda.",
    about:
      "Every director I work with eventually asks why I keep shooting into the last twenty minutes of the day. The honest answer is Asthachal, and they never quite believe me.",
    houses: ["Palm", "Palm", "Amaltash", "Amaltash", "Gulmohar", "Gulmohar", "Jacaranda", "Jacaranda"],
  },
  {
    slug: "leela-varghese",
    name: "Leela Varghese",
    batchYear: 1991,
    batchType: "ISC",
    yearJoined: 1984,
    gradeJoined: 5,
    city: "thiruvananthapuram",
    jobTitle: "Marine Biologist",
    workplace: "Coastal Research Institute",
    bio: "Went from watching birds to counting fish.",
    houses: ["Cauvery", "Cauvery", "Krishna", "Krishna", "Malli", "Malli", "Duranta"],
  },
  {
    slug: "arjun-nair",
    name: "Arjun Nair",
    batchYear: 1994,
    batchType: "ISC",
    yearJoined: 1987,
    gradeJoined: 5,
    city: "singapore",
    jobTitle: "Head of Design",
    workplace: "Meridian Bank",
    bio: "Still cannot draw a straight line without a ruler.",
    houses: ["Takshila", "Takshila", "Alamanda", "Alamanda", "Duranta", "Duranta", "Jacaranda"],
  },
  {
    slug: "priya-mathew",
    name: "Priya Mathew",
    batchYear: 1996,
    batchType: "ISC",
    yearJoined: 1990,
    gradeJoined: 6,
    city: "toronto",
    jobTitle: "Paediatric Nurse",
    bio: "Winters are long here. The valley helps.",
    houses: ["Silver", "Silver", "Golden", "Golden", "Neem", "Neem", "Raavi"],
  },
  {
    slug: "sameer-kulkarni",
    name: "Sameer Kulkarni",
    batchYear: 1999,
    batchType: "ISC",
    yearJoined: 1992,
    gradeJoined: 5,
    city: "berlin",
    jobTitle: "Sound Engineer",
    workplace: "Hafen Studios",
    bio: "Records rooms for a living.",
    about:
      "The quietest place I have ever stood is the far end of the valley at four in the morning, and I have been trying to record something that empty ever since. Nothing comes close. The microphones always hear more than the ears did.",
    houses: ["Green", "Green", "Blue", "Blue", "Meru", "Meru", "Nilgiri", "Nilgiri"],
  },
  {
    slug: "aisha-qureshi",
    name: "Aisha Qureshi",
    batchYear: 2001,
    batchType: "ISC",
    yearJoined: 1994,
    gradeJoined: 5,
    city: "new delhi",
    jobTitle: "Public Health Researcher",
    workplace: "Centre for Equity Studies",
    bio: "Spreadsheets by day. Birdwatching on weekends, badly.",
    houses: ["Red", "Red", "White", "White", "Gulmohar", "Gulmohar", "Amaltash"],
  },
  {
    slug: "nikhil-bose",
    name: "Nikhil Bose",
    batchYear: 2003,
    batchType: "ISC",
    yearJoined: 1996,
    gradeJoined: 5,
    city: "kolkata",
    jobTitle: "Publisher",
    workplace: "Sealdah Books",
    bio: "Publishes poetry nobody buys and everybody quotes.",
    houses: ["Krishna", "Krishna", "Cauvery", "Cauvery", "Malli", "Malli", "Trishul"],
  },
  {
    slug: "divya-reddy",
    name: "Divya Reddy",
    batchYear: 2005,
    batchType: "ISC",
    yearJoined: 1998,
    gradeJoined: 5,
    city: "bengaluru",
    jobTitle: "Founder",
    workplace: "Sarai Learning",
    bio: "Building the school I would have wanted afterwards.",
    about:
      "Ten years in ed-tech taught me that most of it is solving the wrong problem loudly. We run six small learning centres now, all of them rural, none of them with a screen in the room. People find that funny coming from someone who spent a decade building software.",
    houses: ["Jacaranda", "Jacaranda", "Duranta", "Duranta", "Alamanda", "Alamanda", "Takshila"],
  },
  {
    slug: "rohan-pillai",
    name: "Rohan Pillai",
    batchYear: 2007,
    batchType: "ISC",
    yearJoined: 2000,
    gradeJoined: 5,
    city: "san francisco",
    jobTitle: "Staff Engineer",
    workplace: "Latitude",
    bio: "Distributed systems. Undistributed attention span.",
    houses: ["Meru", "Meru", "Kailash", "Kailash", "Trishul", "Trishul", "Nilgiri"],
  },
  {
    slug: "tanvi-shah",
    name: "Tanvi Shah",
    batchYear: 2009,
    batchType: "ISC",
    yearJoined: 2002,
    gradeJoined: 5,
    city: "ahmedabad",
    jobTitle: "Textile Designer",
    workplace: "Indigo & Salt",
    bio: "Natural dyes, mostly. Blue hands permanently.",
    houses: ["Amaltash", "Amaltash", "Gulmohar", "Gulmohar", "Palm", "Palm", "Golden"],
  },
  {
    slug: "kabir-anand",
    name: "Kabir Anand",
    batchYear: 2010,
    batchType: "ISC",
    yearJoined: 2003,
    gradeJoined: 5,
    city: "new york",
    jobTitle: "Jazz Pianist",
    bio: "Learned to keep time at morning assembly.",
    about:
      "There was a piano in the music room with three dead keys and I loved it more than any instrument I have owned since. Somebody eventually fixed it, which I have never entirely forgiven.",
    houses: ["Blue", "Blue", "Green", "Green", "Red", "Red", "Silver", "Silver"],
  },
  {
    slug: "shreya-joshi",
    name: "Shreya Joshi",
    batchYear: 2012,
    batchType: "ISC",
    yearJoined: 2005,
    gradeJoined: 5,
    city: "dubai",
    secondCity: "mumbai",
    jobTitle: "Aviation Meteorologist",
    bio: "Reads clouds professionally now.",
    houses: ["Neem", "Neem", "Raavi", "Raavi", "Malli", "Malli", "Cauvery"],
  },
  {
    slug: "aditya-krishnan",
    name: "Aditya Krishnan",
    batchYear: 2013,
    batchType: "ISC",
    yearJoined: 2006,
    gradeJoined: 5,
    city: "chennai",
    jobTitle: "Veterinarian",
    workplace: "Adyar Animal Clinic",
    bio: "The valley dogs started it.",
    houses: ["White", "White", "Krishna", "Krishna", "Duranta", "Duranta", "Takshila"],
  },
  {
    slug: "ananya-ghosh",
    name: "Ananya Ghosh",
    batchYear: 2014,
    batchType: "ISC",
    yearJoined: 2007,
    gradeJoined: 5,
    city: "edinburgh",
    jobTitle: "PhD Candidate, Ecology",
    workplace: "University of Edinburgh",
    bio: "Studying how birdsong changes near cities.",
    about:
      "My thesis question is basically the one I asked a science teacher in class eight and got told to go and find out for myself. Fifteen years later I am still finding out. She was right, obviously, which is annoying.",
    houses: ["Nilgiri", "Nilgiri", "Meru", "Meru", "Kailash", "Kailash", "Trishul"],
  },
  {
    slug: "yash-agarwal",
    name: "Yash Agarwal",
    batchYear: 2015,
    batchType: "ISC",
    yearJoined: 2010,
    gradeJoined: 8,
    city: "gurugram",
    jobTitle: "Product Manager",
    workplace: "Kettle",
    bio: "Joined in class eight and spent a term being homesick, then never left.",
    houses: ["Gulmohar", "Gulmohar", "Jacaranda", "Jacaranda", "Alamanda"],
  },
  {
    slug: "ishaan-verma",
    name: "Ishaan Verma",
    batchYear: 2016,
    batchType: "ISC",
    yearJoined: 2009,
    gradeJoined: 5,
    city: "bengaluru",
    jobTitle: "Illustrator",
    bio: "Draws birds. Mostly the ones from home.",
    houses: ["Palm", "Palm", "Amaltash", "Amaltash", "Golden", "Golden", "Silver"],
  },
  {
    slug: "meghna-pillai",
    name: "Meghna Pillai",
    batchYear: 2017,
    batchType: "ICSE",
    yearJoined: 2012,
    gradeJoined: 6,
    city: "goa",
    jobTitle: "Chef",
    workplace: "Saltwater",
    bio: "Left after class ten. Still counts the years by houses.",
    houses: ["Cauvery", "Cauvery", "Malli", "Malli", "Krishna"],
  },
  {
    slug: "dhruv-menon",
    name: "Dhruv Menon",
    batchYear: 2018,
    batchType: "ISC",
    yearJoined: 2011,
    gradeJoined: 5,
    city: "boston",
    jobTitle: "Graduate Researcher",
    workplace: "MIT Media Lab",
    bio: "Builds instruments for people who cannot use their hands.",
    houses: ["Duranta", "Duranta", "Takshila", "Takshila", "Alamanda", "Alamanda", "Jacaranda"],
  },
  {
    slug: "sana-mirza",
    name: "Sana Mirza",
    batchYear: 2019,
    batchType: "ISC",
    yearJoined: 2012,
    gradeJoined: 5,
    city: "new delhi",
    jobTitle: "Journalist",
    workplace: "The Wire",
    bio: "Reports on rural education. Started by reporting on the valley.",
    about:
      "My first piece of journalism was a school magazine article arguing that the dining hall should serve breakfast twenty minutes later. It was rejected. I have been slightly better received since.",
    houses: ["Red", "Red", "White", "White", "Blue", "Blue", "Green"],
  },
  {
    slug: "aryan-saxena",
    name: "Aryan Saxena",
    batchYear: 2020,
    batchType: "ISC",
    yearJoined: 2013,
    gradeJoined: 5,
    city: "pune",
    jobTitle: "Software Engineer",
    workplace: "Nirvana Labs",
    bio: "Class of the year nobody got a proper goodbye.",
    houses: ["Meru", "Meru", "Nilgiri", "Nilgiri", "Kailash", "Kailash", "Trishul"],
  },
  {
    slug: "riya-banerjee",
    name: "Riya Banerjee",
    batchYear: 2021,
    batchType: "ISC",
    yearJoined: 2014,
    gradeJoined: 5,
    city: "kolkata",
    jobTitle: "Undergraduate",
    workplace: "Presidency University",
    bio: "Studying history. Blame the valley library.",
    houses: ["Golden", "Golden", "Raavi", "Raavi", "Neem", "Neem", "Palm"],
  },
  {
    slug: "kabir-sethi",
    name: "Kabir Sethi",
    batchYear: 2022,
    batchType: "ISC",
    yearJoined: 2015,
    gradeJoined: 5,
    city: "mumbai",
    jobTitle: "Undergraduate",
    workplace: "Ashoka University",
    bio: "Two years out and already nostalgic. Sorry.",
    houses: ["Alamanda", "Alamanda", "Jacaranda", "Jacaranda", "Duranta", "Duranta", "Takshila"],
  },
  {
    slug: "naina-chopra",
    name: "Naina Chopra",
    batchYear: 2023,
    batchType: "ISC",
    yearJoined: 2016,
    gradeJoined: 5,
    city: "chandigarh",
    jobTitle: "Undergraduate",
    workplace: "Krea University",
    bio: "Currently explaining to everyone what a bird preserve is.",
    houses: ["Krishna", "Krishna", "Cauvery", "Cauvery", "Malli", "Malli", "Amaltash"],
  },
  {
    slug: "vivaan-kapoor",
    name: "Vivaan Kapoor",
    batchYear: 2024,
    batchType: "ISC",
    yearJoined: 2017,
    gradeJoined: 5,
    city: "new delhi",
    jobTitle: "Undergraduate",
    workplace: "St. Stephen's College",
    bio: "Left last year. Still dreams about the bell.",
    houses: ["Silver", "Silver", "Gulmohar", "Gulmohar", "Palm", "Palm", "Golden"],
  },
  {
    slug: "zoya-hussain",
    name: "Zoya Hussain",
    batchYear: 2006,
    batchType: "ISC",
    yearJoined: 1999,
    gradeJoined: 5,
    city: "amsterdam",
    jobTitle: "Urban Planner",
    workplace: "Stadsbureau",
    bio: "Plans cities. Grew up somewhere that was not one.",
    houses: ["Trishul", "Trishul", "Kailash", "Kailash", "Meru", "Meru", "Nilgiri"],
  },
  {
    slug: "harsh-vardhan",
    name: "Harsh Vardhan",
    batchYear: 1997,
    batchType: "ISC",
    yearJoined: 1990,
    gradeJoined: 5,
    city: "jaipur",
    jobTitle: "Conservation Architect",
    bio: "Restores old buildings. Slowly, and on purpose.",
    houses: ["Raavi", "Raavi", "Neem", "Neem", "Golden", "Golden", "Silver"],
  },
  {
    slug: "nandita-rangan",
    name: "Nandita Rangan",
    batchYear: 1993,
    batchType: "ISC",
    yearJoined: 1986,
    gradeJoined: 5,
    city: "mysuru",
    jobTitle: "Classical Vocalist",
    bio: "Sings Carnatic. Learned to listen in the valley.",
    houses: ["Malli", "Malli", "Cauvery", "Cauvery", "Krishna", "Krishna", "Duranta"],
  },
  {
    slug: "imran-baig",
    name: "Imran Baig",
    batchYear: 2002,
    batchType: "ICSE",
    yearJoined: 1997,
    gradeJoined: 7,
    city: "abu dhabi",
    jobTitle: "Airline Captain",
    bio: "Flies wide-bodies. Started with paper ones.",
    houses: ["Blue", "Blue", "Green", "Green", "Red"],
  },
  {
    slug: "sunita-devi",
    name: "Sunita Devi",
    batchYear: 1980,
    batchType: "ISC",
    yearJoined: 1973,
    gradeJoined: 5,
    city: "madanapalle",
    jobTitle: "Retired Headmistress",
    bio: "Left the valley, taught for forty years, came back to live nearby.",
    about:
      "People assume I moved back for nostalgia. I moved back because the light is better and the vegetables are cheaper. The nostalgia is a bonus that arrives most evenings around six.",
    houses: ["White", "White", "Palm", "Palm", "Amaltash", "Amaltash", "Gulmohar"],
  },

  // ── Faculty. The directory has a Teachers tab and it should not be empty. ──
  {
    slug: "gita-raman",
    name: "Gita Raman",
    accountType: "teacher",
    city: "rishi valley",
    jobTitle: "Teacher of Biology",
    subjects: "Biology, Nature Club",
    taughtFrom: 2004,
    taughtUntil: null,
    bio: "Twenty one years of pointing at trees until somebody looks.",
    about:
      "I tell every new batch the same thing on the first walk: you will not remember the syllabus, you will remember the paradise flycatcher, and that is a perfectly good outcome for a biology class.",
  },
  {
    slug: "peter-dsouza",
    name: "Peter D'Souza",
    accountType: "ex_teacher",
    city: "goa",
    jobTitle: "Former Teacher of English",
    subjects: "English, Theatre",
    taughtFrom: 1986,
    taughtUntil: 2012,
    bio: "Twenty six years of Shakespeare under a tamarind tree.",
  },
  {
    slug: "lakshmi-narayanan",
    name: "Lakshmi Narayanan",
    accountType: "teacher",
    city: "rishi valley",
    jobTitle: "Teacher of Mathematics",
    subjects: "Mathematics",
    taughtFrom: 2011,
    taughtUntil: null,
    bio: "Believes there is no such thing as a person who is bad at maths.",
  },
  {
    slug: "ramesh-babu",
    name: "Ramesh Babu",
    accountType: "ex_teacher",
    city: "tirupati",
    jobTitle: "Former Teacher of Physics",
    subjects: "Physics, Astronomy Club",
    taughtFrom: 1979,
    taughtUntil: 2009,
    bio: "Ran the telescope evenings for thirty years.",
    about:
      "The valley sky is the reason half of you can find Orion. It is also the reason I never took a posting in a city. You cannot unsee a sky like that, and you certainly cannot swap it for streetlights.",
  },
  {
    slug: "farida-contractor",
    name: "Farida Contractor",
    accountType: "teacher",
    city: "rishi valley",
    jobTitle: "Teacher of Art",
    subjects: "Art, Pottery",
    taughtFrom: 1998,
    taughtUntil: null,
    bio: "The pottery shed is open. It has always been open.",
  },
];

/** Everyone the seeder writes, visitor first. */
export const ALL_DEMO_PEOPLE: DemoPerson[] = [DEMO_VISITOR, ...DEMO_PEOPLE];
